In [1]:
from _utils import *

In [ ]:
raw_json_df = pd.read_json(JSON_FP)
annotations_df = pd.read_excel(ANNOTATIONaS_FP)

HTTP_ERROR_LIST = raw_json_df.query("error_code.notna()")[["row_id"]]["row_id"].tolist()
INNA_ERROR_LIST = annotations_df.query("subtype_1 == 'Exclude - Not on Model DB'")[["row_id"]]["row_id"].tolist()
a = set(HTTP_ERROR_LIST)
b = set(INNA_ERROR_LIST)

/home/imc33/.conda/envs/mod-annotation/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
/home/imc33/.conda/envs/mod-annotation/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed

In [13]:
#Things in my list that aren't online
EXTRA_ERRORS = list(b-a)
View(raw_json_df.query("row_id in @EXTRA_ERRORS")[["url"]])

                                                                                  url
121      https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/ExIAF.mod
245      https://modeldb.science/230811?tab=2&file=PapoutsiEtAl2017/mod_files/cad.mod
596              https://modeldb.science/151460?tab=2&file=MiocinovicEtAl2006/KDR.mod
960     https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/InhIAF.mod
1007  https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/EPlasSom.mod
1021     https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/PACEF.MOD
1025  https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/EPlasSyn.mod
1168  https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/EPlasInp.mod

In [12]:
View(raw_json_df.query("has_include == 1")[["url"]].reset_index(drop=True))

                                                                                 url
0   https://modeldb.science/254217?tab=2&file=GidonEtAl2020_fig3andS9/_mod/mySyn.mod
1                        https://modeldb.science/136095?tab=2&file=ncdemo/GABAar.mod
2                        https://modeldb.science/51022?tab=2&file=amirdevor03/fh.mod
3            https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/inak.mod
4                       https://modeldb.science/9889?tab=2&file=lytton97/GABALOW.mod
5                         https://modeldb.science/7399?tab=2&file=lytton98/GABAA.mod
6                         https://modeldb.science/136095?tab=2&file=ncdemo/NMDAr.mod
7                       https://modeldb.science/12631?tab=2&file=lytton97b/GABAA.mod
8                             https://modeldb.science/35358?tab=2&file=35358/cal.mod
9                       https://modeldb.science/12631?tab=2&file=lytton97b/pulse.mod
10                      https://modeldb.science/144490?tab=2&file=bpap/nmda_andr.mod
11              https://modeldb.science/182134?tab=2&file=hfo_model/mod/kaolmkop.mod
12                  https://modeldb.science/37819?tab=2&file=thal_aug_resp/nstim.mod
13                       https://modeldb.science/84589?tab=2&file=eaps/mod/hsoma.mod
14                        https://modeldb.science/74298?tab=2&file=sth-model/HVA.mod
15                https://modeldb.science/182134?tab=2&file=hfo_model/mod/kahppr.mod
16                         https://modeldb.science/84589?tab=2&file=eaps/mod/cat.mod
17                         https://modeldb.science/9889?tab=2&file=lytton97/AMPA.mod
18            https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/isi.mod
19                      https://modeldb.science/84589?tab=2&file=eaps/mod/kaprox.mod
20                        https://modeldb.science/136095?tab=2&file=ncdemo/AMPAr.mod
21                    https://modeldb.science/37819?tab=2&file=thal_aug_resp/kdr.mod
22              https://modeldb.science/182134?tab=2&file=hfo_model/mod/kapyrkop.mod
23                         https://modeldb.science/84589?tab=2&file=eaps/mod/can.mod
24                     https://modeldb.science/12631?tab=2&file=lytton97b/pregen.mod
25                     https://modeldb.science/116859?tab=2&file=ctxnet_v7/GABAa.mod
26               https://modeldb.science/186768?tab=2&file=SanjayEtAl2015/iholmw.mod
27              https://modeldb.science/182134?tab=2&file=hfo_model/mod/iholmkop.mod
28                       https://modeldb.science/185858?tab=2&file=CaHDemo/ihlts.mod
29              https://modeldb.science/182134?tab=2&file=hfo_model/mod/ihpyrkop.mod
30                   https://modeldb.science/37819?tab=2&file=thal_aug_resp/AMPA.mod
31             https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/if.mod
32        https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/cadynam.mod
33             https://modeldb.science/182134?tab=2&file=hfo_model/mod/nafolmkop.mod
34                       https://modeldb.science/9889?tab=2&file=lytton97/GABAB1.mod
35          https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/inaca.mod
36                          https://modeldb.science/7400?tab=2&file=lytton99/kdr.mod
37            https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/ibg.mod
38                   https://modeldb.science/64229?tab=2&file=netmod/parbush/nap.mod

In [1]:
from _utils import *

raw_json_df = pd.read_json(JSON_FP)
MODEL_IDS = set(map(str, raw_json_df["model_id"].tolist()))  # use set for fast lookup
print(f"Loaded {len(MODEL_IDS)} model IDs")

base_path = Path(DROPBOX_DIR)
working_dir = Path.cwd()

zip_files = [
    item for item in base_path.iterdir()
    if item.suffix == ".zip" and item.stem in MODEL_IDS
]
print(f"Found {len(zip_files)} matching zip files out of {len(list(base_path.glob('*.zip')))} total")

Loaded 457 model IDs
Found 288 matching zip files out of 1521 total