In [1]:
from _utils import *

In [ ]:
raw_json_df = pd.read_json(JSON_FP)
annotations_df = pd.read_excel(ANNOTATIONaS_FP)

HTTP_ERROR_LIST = raw_json_df.query("error_code.notna()")[["row_id"]]["row_id"].tolist()
INNA_ERROR_LIST = annotations_df.query("subtype_1 == 'Exclude - Not on Model DB'")[["row_id"]]["row_id"].tolist()
a = set(HTTP_ERROR_LIST)
b = set(INNA_ERROR_LIST)

/home/imc33/.conda/envs/mod-annotation/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
/home/imc33/.conda/envs/mod-annotation/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed

In [13]:
#Things in my list that aren't online
EXTRA_ERRORS = list(b-a)
View(raw_json_df.query("row_id in @EXTRA_ERRORS")[["url"]])

                                                                                  url
121      https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/ExIAF.mod
245      https://modeldb.science/230811?tab=2&file=PapoutsiEtAl2017/mod_files/cad.mod
596              https://modeldb.science/151460?tab=2&file=MiocinovicEtAl2006/KDR.mod
960     https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/InhIAF.mod
1007  https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/EPlasSom.mod
1021     https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/PACEF.MOD
1025  https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/EPlasSyn.mod
1168  https://modeldb.science/121628?tab=2&file=Swimmy/SwimmyGUI/nrnpgms/EPlasInp.mod

In [12]:
View(raw_json_df.query("has_include == 1")[["url"]].reset_index(drop=True))

                                                                                 url
0   https://modeldb.science/254217?tab=2&file=GidonEtAl2020_fig3andS9/_mod/mySyn.mod
1                        https://modeldb.science/136095?tab=2&file=ncdemo/GABAar.mod
2                        https://modeldb.science/51022?tab=2&file=amirdevor03/fh.mod
3            https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/inak.mod
4                       https://modeldb.science/9889?tab=2&file=lytton97/GABALOW.mod
5                         https://modeldb.science/7399?tab=2&file=lytton98/GABAA.mod
6                         https://modeldb.science/136095?tab=2&file=ncdemo/NMDAr.mod
7                       https://modeldb.science/12631?tab=2&file=lytton97b/GABAA.mod
8                             https://modeldb.science/35358?tab=2&file=35358/cal.mod
9                       https://modeldb.science/12631?tab=2&file=lytton97b/pulse.mod
10                      https://modeldb.science/144490?tab=2&file=bpap/nmda_andr.mod
11              https://modeldb.science/182134?tab=2&file=hfo_model/mod/kaolmkop.mod
12                  https://modeldb.science/37819?tab=2&file=thal_aug_resp/nstim.mod
13                       https://modeldb.science/84589?tab=2&file=eaps/mod/hsoma.mod
14                        https://modeldb.science/74298?tab=2&file=sth-model/HVA.mod
15                https://modeldb.science/182134?tab=2&file=hfo_model/mod/kahppr.mod
16                         https://modeldb.science/84589?tab=2&file=eaps/mod/cat.mod
17                         https://modeldb.science/9889?tab=2&file=lytton97/AMPA.mod
18            https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/isi.mod
19                      https://modeldb.science/84589?tab=2&file=eaps/mod/kaprox.mod
20                        https://modeldb.science/136095?tab=2&file=ncdemo/AMPAr.mod
21                    https://modeldb.science/37819?tab=2&file=thal_aug_resp/kdr.mod
22              https://modeldb.science/182134?tab=2&file=hfo_model/mod/kapyrkop.mod
23                         https://modeldb.science/84589?tab=2&file=eaps/mod/can.mod
24                     https://modeldb.science/12631?tab=2&file=lytton97b/pregen.mod
25                     https://modeldb.science/116859?tab=2&file=ctxnet_v7/GABAa.mod
26               https://modeldb.science/186768?tab=2&file=SanjayEtAl2015/iholmw.mod
27              https://modeldb.science/182134?tab=2&file=hfo_model/mod/iholmkop.mod
28                       https://modeldb.science/185858?tab=2&file=CaHDemo/ihlts.mod
29              https://modeldb.science/182134?tab=2&file=hfo_model/mod/ihpyrkop.mod
30                   https://modeldb.science/37819?tab=2&file=thal_aug_resp/AMPA.mod
31             https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/if.mod
32        https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/cadynam.mod
33             https://modeldb.science/182134?tab=2&file=hfo_model/mod/nafolmkop.mod
34                       https://modeldb.science/9889?tab=2&file=lytton97/GABAB1.mod
35          https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/inaca.mod
36                          https://modeldb.science/7400?tab=2&file=lytton99/kdr.mod
37            https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/ibg.mod
38                   https://modeldb.science/64229?tab=2&file=netmod/parbush/nap.mod

In [ ]:
raw_json_df["model_id"].tolist()

[183300,
 223649,
 3511,
 262115,
 150288,
 150288,
 186768,
 124063,
 143633,
 254217,
 144541,
 2014814,
 19920,
 112086,
 144376,
 151825,
 222321,
 136095,
 237469,
 267067,
 267189,
 17664,
 2017405,
 51022,
 124524,
 141273,
 187615,
 258867,
 243448,
 184139,
 116862,
 228599,
 144490,
 267508,
 267140,
 64228,
 187604,
 58173,
 3808,
 241169,
 244416,
 222716,
 168414,
 21329,
 267669,
 266498,
 65218,
 153574,
 225080,
 38241,
 256140,
 114355,
 139657,
 123927,
 267511,
 257028,
 87473,
 138382,
 222321,
 266864,
 267293,
 147218,
 266498,
 74298,
 239878,
 2014832,
 124394,
 119266,
 267691,
 267661,
 244414,
 223649,
 135787,
 147141,
 121253,
 150538,
 93321,
 184497,
 266814,
 266775,
 145836,
 243508,
 237595,
 267511,
 136095,
 244679,
 232023,
 3434,
 266498,
 186977,
 7907,
 138205,
 2017405,
 2015953,
 237594,
 119266,
 267176,
 222321,
 223649,
 267499,
 267009,
 239582,
 170030,
 150446,
 118662,
 82849,
 2015410,
 239582,
 155735,
 222321,
 187473,
 223649,
 144520,
 98017,
 2015410,
 2937,
 182134,
 37857,
 2014814,
 267293,
 120910,
 121628,
 183300,
 97868,
 153196,
 225080,
 243841,
 143719,
 184497,
 267501,
 9889,
 2017143,
 143719,
 144089,
 153280,
 150288,
 2017005,
 82849,
 236310,
 260971,
 85112,
 58173,
 258854,
 141272,
 7399,
 266578,
 150240,
 136095,
 12631,
 151460,
 143671,
 124043,
 143633,
 266578,
 37857,
 266782,
 228599,
 2016658,
 267146,
 230137,
 28316,
 267088,
 184732,
 183949,
 150288,
 82784,
 267293,
 257028,
 19214,
 151482,
 267511,
 147867,
 97863,
 184497,
 2014814,
 185858,
 267666,
 44050,
 126637,
 222716,
 97860,
 18500,
 143633,
 182758,
 97882,
 2016601,
 12631,
 223649,
 28316,
 105385,
 139883,
 50997,
 258854,
 232023,
 144376,
 244416,
 141063,
 168148,
 112685,
 267221,
 266782,
 148094,
 237595,
 207695,
 235769,
 38229,
 143719,
 3800,
 143072,
 136715,
 18198,
 123927,
 150556,
 153574,
 144589,
 244679,
 3807,
 266498,
 267103,
 194897,
 139657,
 262115,
 62673,
 169240,
 206364,
 94321,
 140249,
 249705,
 53965,
 2014816,
 187603,
 167772,
 257028,
 144490,
 37819,
 17664,
 239421,
 120910,
 223649,
 206267,
 143719,
 148253,
 232023,
 146949,
 241240,
 230811,
 241240,
 237653,
 64228,
 185328,
 239878,
 187473,
 2017143,
 257028,
 2017143,
 266814,
 147867,
 249463,
 136309,
 3434,
 2001735,
 226401,
 143719,
 124063,
 114394,
 184139,
 267267,
 35358,
 181967,
 183300,
 138379,
 2017405,
 128446,
 223649,
 267511,
 267293,
 167772,
 153196,
 3808,
 232813,
 231818,
 20756,
 151460,
 125385,
 12631,
 139654,
 124063,
 138382,
 182134,
 267509,
 148253,
 53569,
 38229,
 3289,
 3483,
 183300,
 2016137,
 144511,
 119266,
 266864,
 186768,
 144549,
 267617,
 267146,
 185330,
 3793,
 182797,
 154732,
 151460,
 113446,
 237653,
 144549,
 246546,
 144538,
 123927,
 267621,
 2017143,
 2016601,
 246546,
 223649,
 140828,
 64229,
 3342,
 144482,
 58173,
 241165,
 185123,
 64228,
 139883,
 2015410,
 17664,
 138321,
 267599,
 3658,
 184497,
 98017,
 190140,
 7399,
 267621,
 267646,
 140462,
 2017405,
 54903,
 267499,
 259366,
 110560,
 266799,
 58173,
 105385,
 150691,
 267694,
 87585,
 9888,
 38240,
 144490,
 232023,
 267646,
 62266,
 2017143,
 239177,
 53451,
 267499,
 80769,
 2017143,
 187603,
 244922,
 3810,
 241240,
 144482,
 182134,
 266925,
 144490,
 97860,
 62284,
 156733,
 217783,
 266578,
 241240,
 186977,
 37819,
 206364,
 244679,
 144579,
 65218,
 262373,
 267189,
 151460,
 237595,
 256024,
 267617,
 51196,
 127021,
 144482,
 114355,
 182134,
 267694,
 267184,
 258854,
 38241,
 84589,
 53876,
 116094,
 37857,
 2014832,
 144511,
 35358,
 65218,
 266782,
 60136,
 80769,
 140249,
 2016658,
 58173,
 257028,
 267511,
 65218,
 37857,
 121600,
 157157,
 65218,
 184333,
 150288,
 150288,
 2017143,
 266850,
 3264,
 153196,
 267646,
 50210,
 243841,
 151126,
 232023,
 150288,
 153574,
 207695,
 114685,
 267501,
 146565,
 144490,
 266989,
 267508,
 18500,
 37970,
 112685,
 238892,
 168414,
 2017403,
 267511,
 266900,
 126637,
 150288,
 150446,
 186977,
 240960,
 249705,
 116096,
 243842,
 65218,
 241160,
 217783,
 86537,
 267088,
 168414,
 231818,
 266818,
 2017405,
 58173,
 116983,
 136026,
 18502,
 256140,
 82894,
 168858,
 249705,
 256024,
 266818,
 124394,
 141272,
 222321,
 267511,
 28316,
 195666,
 83547,
 2014998,
 181967,
 223891,
 243446,
 155796,
 184054,
 147218,
 267511,
 150551,
 84589,
 182797,
 3800,
 123623,
 38229,
 2016666,
 74298,
 2016601,
 267306,
 266806,
 126640,
 266814,
 106891,
 143719,
 267610,
 139883,
 267293,
 157157,
 19176,
 243841,
 144089,
 144482,
 143633,
 143635,
 224923,
 266811,
 267666,
 144450,
 267621,
 182134,
 124063,
 267293,
 3434,
 33975,
 144372,
 38241,
 260971,
 124525,
 80769,
 267669,
 144089,
 168414,
 186768,
 2017143,
 151482,
 146030,
 37856,
 152197,
 94321,
 151282,
 257028,
 256024,
 187610,
 267599,
 84589,
 267293,
 266818,
 113435,
 256632,
 267103,
 74298,
 168148,
 37819,
 169240,
 223649,
 266732,
 2017143,
 223031,
 114355,
 267621,
 98005,
 183300,
 266578,
 267710,
 9889,
 58173,
 249705,
 38240,
 267646,
 147218,
 267646,
 53876,
 114355,
 262670,
 51196,
 267508,
 146030,
 267661,
 267666,
 3815,
 19491,
 267391,
 181967,
 114652,
 232023,
 267646,
 2016601,
 183300,
 37819,
 184497,
 187604,
 243508,
 141272,
 267511,
 151460,
 7907,
 232023,
 146949,
 267221,
 144520,
 267357,
 244848,
 116859,
 62266,
 144579,
 93321,
 267106,
 87454,
 95960,
 144579,
 2017143,
 46839,
 267710,
 144586,
 118631,
 83547,
 65218,
 3343,
 125689,
 84589,
 3802,
 267669,
 153280,
 136095,
 141272,
 185355,
 146030,
 267599,
 249705,
 120692,
 93326,
 157157,
 189786,
 231427,
 2017143,
 267666,
 222321,
 117459,
 267176,
 37819,
 246546,
 182134,
 18501,
 151825,
 266864,
 266799,
 98005,
 114355,
 267599,
 267088,
 267501,
 258738,
 114355,
 266900,
 98017,
 145836,
 125385,
 267666,
 267267,
 266818,
 237595,
 153574,
 2016666,
 267189,
 150288,
 121253,
 151282,
 143072,
 64229,
 124043,
 258738,
 247968,
 267646,
 185330,
 244687,
 267293,
 155057,
 143633,
 267221,
 267595,
 223649,
 222359,
 223649,
 126814,
 39949,
 38241,
 46839,
 266851,
 267221,
 64229,
 136095,
 267306,
 249463,
 144450,
 168858,
 267646,
 184732,
 267106,
 143633,
 267067,
 267189,
 3343,
 155705,
 157157,
 157157,
 267009,
 267088,
 258854,
 39949,
 51196,
 260972,
 257028,
 244922,
 267710,
 259732,
 84589,
 257028,
 257028,
 264834,
 7907,
 138273,
 259366,
 245415,
 185858,
 267176,
 266498,
 206400,
 257027,
 53876,
 244687,
 222726,
 267501,
 12631,
 260967,
 144450,
 239421,
 267754,
 266872,
 97882,
 82784,
 113446,
 187604,
 83547,
 2017143,
 266851,
 2017143,
 150288,
 185355,
 3658,
 54903,
 267599,
 120910,
 266900,
 185332,
 267146,
 46839,
 123927,
 267501,
 183949,
 267501,
 182797,
 239421,
 240116,
 157157,
 153280,
 223962,
 150284,
 2017405,
 98017,
 38241,
 38241,
 151949,
 182797,
 64229,
 157157,
 150556,
 267221,
 226010,
 237653,
 249705,
 266775,
 231818,
 38241,
 26997,
 143633,
 38241,
 151126,
 267509,
 127388,
 184333,
 257028,
 244922,
 146565,
 243448,
 182797,
 257028,
 267589,
 113446,
 2014832,
 3800,
 251493,
 116094,
 236310,
 267599,
 249705,
 153574,
 186977,
 259261,
 38241,
 181967,
 185355,
 140249,
 267511,
 144579,
 239421,
 267669,
 266900,
 95960,
 267754,
 125689,
 267267,
 184333,
 116859,
 266984,
 151282,
 105385,
 267311,
 236310,
 266775,
 139654,
 223649,
 238332,
 186977,
 267146,
 266989,
 124291,
 195615,
 3682,
 243508,
 157157,
 150288,
 17664,
 260971,
 187604,
 147461,
 114685,
 266818,
 267621,
 151443,
 167694,
 144376,
 222716,
 265523,
 186768,
 232023,
 182134,
 65218,
 38241,
 267499,
 267499,
 267599,
 266864,
 98017,
 151443,
 33975,
 267710,
 230137,
 185858,
 136309,
 3658,
 3808,
 182134,
 136095,
 267221,
 117207,
 2017405,
 151458,
 187615,
 223649,
 267221,
 267103,
 3660,
 267754,
 2017403,
 267661,
 266984,
 244679,
 2015410,
 154732,
 46839,
 136309,
 136023,
 112685,
 244848,
 261435,
 53451,
 37970,
 3488,
 267499,
 127388,
 267646,
 147867,
 267621,
 267754,
 156034,
 151458,
 258867,
 37970,
 2014832,
 267176,
 113446,
 151126,
 143604,
 143633,
 249705,
 266802,
 241240,
 240960,
 185123,
 232813,
 140462,
 144502,
 266775,
 3648,
 153280,
 136023,
 151460,
 266864,
 244922,
 267694,
 98005,
 3817,
 64229,
 93321,
 93326,
 144490,
 114355,
 155705,
 74298,
 267221,
 122329,
 3808,
 258738,
 114355,
 144549,
 37819,
 3807,
 239421,
 2017006,
 267599,
 167772,
 244416,
 37819,
 231427,
 267088,
 150288,
 267066,
 125689,
 121628,
 150288,
 147141,
 223649,
 267646,
 267589,
 116862,
 184333,
 116862,
 150288,
 136023,
 266814,
 3511,
 157157,
 182134,
 266818,
 20756,
 267176,
 267357,
 267511,
 38241,
 170030,
 139656,
 2014816,
 18500,
 151126,
 267768,
 144579,
 153280,
 249463,
 112834,
 256388,
 266802,
 232023,
 243448,
 58173,
 53569,
 138382,
 37857,
 87473,
 ...]