In [1]:
from _utils import *
METADATA_FP = os.path.join(RAW_DATA_DIR, "model_db_metadata.json")
raw_json_df = pd.read_json(METADATA_FP)

In [2]:
View(raw_json_df.query("has_include == 1")[["url"]])

                                                                                   url
9     https://modeldb.science/254217?tab=2&file=GidonEtAl2020_fig3andS9/_mod/mySyn.mod
17                         https://modeldb.science/136095?tab=2&file=ncdemo/GABAar.mod
23                         https://modeldb.science/51022?tab=2&file=amirdevor03/fh.mod
36                       https://modeldb.science/187604?tab=2&file=modeldbca1/xtra.mod
112            https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/inak.mod
130                       https://modeldb.science/9889?tab=2&file=lytton97/GABALOW.mod
144                         https://modeldb.science/7399?tab=2&file=lytton98/GABAA.mod
147                         https://modeldb.science/136095?tab=2&file=ncdemo/NMDAr.mod
148                       https://modeldb.science/12631?tab=2&file=lytton97b/GABAA.mod
214               https://modeldb.science/144589?tab=2&file=BerzThetaGamm2013/xtra.mod
267                             https://modeldb.science/35358?tab=2&file=35358/cal.mod
284                       https://modeldb.science/12631?tab=2&file=lytton97b/pulse.mod
354                       https://modeldb.science/144490?tab=2&file=bpap/nmda_andr.mod
369               https://modeldb.science/182134?tab=2&file=hfo_model/mod/kaolmkop.mod
379                   https://modeldb.science/37819?tab=2&file=thal_aug_resp/nstim.mod
492                        https://modeldb.science/84589?tab=2&file=eaps/mod/hsoma.mod
498                         https://modeldb.science/74298?tab=2&file=sth-model/HVA.mod
521                 https://modeldb.science/182134?tab=2&file=hfo_model/mod/kahppr.mod
546                          https://modeldb.science/84589?tab=2&file=eaps/mod/cat.mod
566                          https://modeldb.science/9889?tab=2&file=lytton97/AMPA.mod
601             https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/isi.mod
621                       https://modeldb.science/84589?tab=2&file=eaps/mod/kaprox.mod
625                         https://modeldb.science/136095?tab=2&file=ncdemo/AMPAr.mod
641                     https://modeldb.science/37819?tab=2&file=thal_aug_resp/kdr.mod
643               https://modeldb.science/182134?tab=2&file=hfo_model/mod/kapyrkop.mod
717                          https://modeldb.science/84589?tab=2&file=eaps/mod/can.mod
734                      https://modeldb.science/12631?tab=2&file=lytton97b/pregen.mod
824                      https://modeldb.science/116859?tab=2&file=ctxnet_v7/GABAa.mod
855                https://modeldb.science/186768?tab=2&file=SanjayEtAl2015/iholmw.mod
857               https://modeldb.science/182134?tab=2&file=hfo_model/mod/iholmkop.mod
869                        https://modeldb.science/185858?tab=2&file=CaHDemo/ihlts.mod
873               https://modeldb.science/182134?tab=2&file=hfo_model/mod/ihpyrkop.mod
947                    https://modeldb.science/37819?tab=2&file=thal_aug_resp/AMPA.mod
1014             https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/if.mod
1023        https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/cadynam.mod
1040             https://modeldb.science/182134?tab=2&file=hfo_model/mod/nafolmkop.mod
1144                       https://modeldb.science/9889?tab=2&file=lytton97/GABAB1.mod
1166          https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/inaca.mod
1211                          https://modeldb.science/7400?tab=2&file=lytton99/kdr.mod
1216            https://modeldb.science/144520?tab=2&file=DiFrancescoNoble1985/ibg.mod
1236                   https://modeldb.science/64229?tab=2&file=netmod/parbush/nap.mod

Loading metadata from /nfs/roberts/project/pi_rm693/imc33/mod-annotation/data/raw/model_db_metadata.json
Loaded metadata with 1297 entries
Found 41 MOD files with INCLUDE statements
Scanning parent directories for .inc files...

  0%|          | 0/41 [00:00<?, ?it/s]

100%|██████████| 41/41 [00:02<00:00, 13.92it/s]

In [4]:
files_with_includes

,row_id,file_hash,raw_sha,count,url,download_url,filename,content,error_code,has_include,download_date
9,10,a60a597677abbb4b755e0c0ecc6bc3ccb4a013bdcaba16...,9e58366f7bed865d583439908aaabb0522769e24f4d065...,1,https://modeldb.science/254217?tab=2&file=Gido...,https://modeldb.science/getModelFile?model=254...,GidonEtAl2020_fig3andS9/_mod/mySyn.mod,\nCOMMENT\n\n\nUse only what is in ISyn and IU...,None,1,2025-10-19 15:13:55
17,18,d21365cb949fb3f9c01c652c39aa84262012e536ceb6c9...,3a8be119a84f08f064463d859c9dbc24f2bed23997ac8b...,1,https://modeldb.science/136095?tab=2&file=ncde...,https://modeldb.science/getModelFile?model=136...,ncdemo/GABAar.mod,NEURON { POINT_PROCESS GABAar }\n\nPARAMETER ...,None,1,2025-10-19 15:13:56
23,24,fdc16c53e18ef0ba78daf28cd1b723a6be60296758de52...,1d7f7d44476384604f7d1b5aa931914e72ce2e039d6b13...,1,https://modeldb.science/51022?tab=2&file=amird...,https://modeldb.science/getModelFile?model=510...,amirdevor03/fh.mod,TITLE FH channel\r\n: Frankenhaeuser - Huxley ...,None,1,2025-10-19 15:13:56
36,37,1eb9f62f592115967bb9d3c1e99679339273c0eafa89bd...,17c820718a0d8f1fd853125d7d84645b225fd3b1ec97c7...,1,https://modeldb.science/187604?tab=2&file=mode...,https://modeldb.science/getModelFile?model=187...,modeldbca1/xtra.mod,": $Id: xtra.mod,v 1.3 2009/02/24 00:52:07 ted ...",None,1,2025-10-19 15:13:57
112,113,4eab8a3cf38b5ebf6a412a5fc3ea967f50fe97268993a9...,708a414651fa47c04b304535361797b0ce5fca469f7a5f...,1,https://modeldb.science/144520?tab=2&file=DiFr...,https://modeldb.science/getModelFile?model=144...,DiFrancescoNoble1985/inak.mod,TITLE Na+/K+ pump current\r\nCOMMENT\r\n\tmodi...,None,1,2025-10-19 15:14:03
130,131,aeaa32102ec4a98a08d51c98d6323d900b285b408cd83d...,b667bcf23164b2b0abd10e52e45201c52e87caf765a57f...,1,https://modeldb.science/9889?tab=2&file=lytton...,https://modeldb.science/getModelFile?model=988...,lytton97/GABALOW.mod,NEURON { POINT_PROCESS GABALOW }\n: GABA SY...,None,1,2025-10-19 15:14:04
144,145,470bf7bdf1af2732b1e95b6b804d183d3686b2b6d5ff1d...,6464120cd61f938abeb9ff0592d5f83b9cf7628b58d06f...,1,https://modeldb.science/7399?tab=2&file=lytton...,https://modeldb.science/getModelFile?model=739...,lytton98/GABAA.mod,NEURON { POINT_PROCESS GABAA }\n: GABA SYNA...,None,1,2025-10-19 15:14:05
147,148,4b45d21388eec84b52f561903cd021f441015f45c85e41...,41149457a4ac8bf219a506b30c1ccd489dced3ec2c3757...,1,https://modeldb.science/136095?tab=2&file=ncde...,https://modeldb.science/getModelFile?model=136...,ncdemo/NMDAr.mod,NEURON{ POINT_PROCESS NMDAr\n RANGE B \n GLO...,None,1,2025-10-19 15:14:05
148,149,c73b80f66376f8903f42dc702da273c3523a9087e20f74...,caa258dcdb18bb086c5b8603bbe7167b513070cc1c9524...,1,https://modeldb.science/12631?tab=2&file=lytto...,https://modeldb.science/getModelFile?model=126...,lytton97b/GABAA.mod,NEURON { POINT_PROCESS GABAA }\n: GABA SYNA...,None,1,2025-10-19 15:14:05
214,215,aec23cd9b58c8b80eafae737724ab6303aa80ee6a780e0...,f5c3d45802dd0fa4d6cab7babf8dfc7df7a9b1919ef01d...,1,https://modeldb.science/144589?tab=2&file=Berz...,https://modeldb.science/getModelFile?model=144...,BerzThetaGamm2013/xtra.mod,COMMENT\r\nThis mechanism is intended to be us...,None,1,2025-10-19 15:14:10
267,268,cf61cb0ac4b0e1ab5230b994e5701deea8540388630454...,1a3a593c8ba6907a83532d143adafffb08da43fdfae303...,1,https://modeldb.science/35358?tab=2&file=35358...,https://modeldb.science/getModelFile?model=353...,35358/cal.mod,NEURON { SUFFIX cal }\nNEURON { USEION ca WRIT...,None,1,2025-10-19 15:14:14
284,286,4375ed0f480cbe4572e4b30abcffe052bed63a65aa0265...,ff50fd3038727cc99c90938ade94903bf349d60e8a08c3...,1,https://modeldb.science/12631?tab=2&file=lytto...,https://modeldb.science/getModelFile?model=126...,lytton97b/pulse.mod,": $Id: pulse.mod,v 1.1 1998/07/21 13:54:10 bil...",None,1,2025-10-19 15:14:15
354,356,6c27633fce64e5c8c36038b5d1d72376f4e04abcea8990...,2d0197598c104c9388e785a068f0cb9930f36b56c9ce79...,1,https://modeldb.science/144490?tab=2&file=bpap...,https://modeldb.science/getModelFile?model=144...,bpap/nmda_andr.mod,COMMENT\n\nAMPA synapse with two decay time co...,None,1,2025-10-19 15:14:20
369,371,1e47dfd343d0bed6630ec508e86d32fe62dae51a242b97...,2f041f1a0619a67b7876760956aaf5a91f570fc3faa539...,8,https://modeldb.science/182134?tab=2&file=hfo_...,https://modeldb.science/getModelFile?model=182...,hfo_model/mod/kaolmkop.mod,COMMENT\n\n//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%...,None,1,2025-10-19 15:14:21
379,381,0bc08be0d006feda991c15eb9281621209eb30e3d848f3...,438325dd4b4d1dc6439979e3ece8fbcea905f23d845006...,1,https://modeldb.science/37819?tab=2&file=thal_...,https://modeldb.science/getModelFile?model=378...,thal_aug_resp/nstim.mod,": $Id: nstim.mod,v 1.5 2004/03/15 22:43:00 bil...",None,1,2025-10-19 15:14:22
492,494,3ad5b20f42e6f26a02dc46faca8b9cecb818086297eb45...,97f5a78aeccf32a7c237f49376fc7437343f1755bbfffb...,1,https://modeldb.science/84589?tab=2&file=eaps/...,https://modeldb.science/getModelFile?model=845...,eaps/mod/hsoma.mod,: Copyright (c) California Institute of Techno...,None,1,2025-10-19 15:14:32
498,500,69b9b260751b45969472fb5738ede4cccd302644ca34b2...,43f4d2e26d58a9017aa720cb13e96950a45a5ff9fd7b78...,1,https://modeldb.science/74298?tab=2&file=sth-m...,https://modeldb.science/getModelFile?model=742...,sth-model/HVA.mod,TITLE calcium HVA channels for STh\n\nCOMMENT\...,None,1,2025-10-19 15:14:32
521,523,7956137d31f76eee12d884bcb1e3c7f8400d03e687ac6b...,5fc3b0156b2e0e18269c0e26ae40ae407480948940de13...,8,https://modeldb.science/182134?tab=2&file=hfo_...,https://modeldb.science/getModelFile?model=182...,hfo_model/mod/kahppr.mod,COMMENT\n\n//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%...,None,1,2025-10-19 15:14:37
546,548,cc449c78632dd81ba77c27990d30bbbd428a1c840b9dd9...,5457e9cb365eb4282d46b8b2840a4bd2cb20f2483e9518...,1,https://modeldb.science/84589?tab=2&file=eaps/...,https://modeldb.science/getModelFile?model=845...,eaps/mod/cat.mod,: Copyright (c) California Institute of Techno...,None,1,2025-10-19 15:14:39
566,568,ecb18e2aee7f2e5e99d8a399446ddac7216b5d9fe2c67e...,87e3992133d25b553285f8c8bb83f4b6122cbaf651121f...,1,https://modeldb.science/9889?tab=2&file=lytton...,https://modeldb.science/getModelFile?model=988...,lytton97/AMPA.mod,NEURON { POINT_PROCESS AMPA }\n: GLUTAMAT...,None,1,2025-10-19 15:14:40
601,603,84adc8f66c540e937bf2bb0715d487ed2389ac3a2446db...,231363284fe84b49b2b325881e54456f91166024911e73...,1,https://modeldb.science/144520?tab=2&file=DiFr...,https://modeldb.science/getModelFile?model=144...,DiFrancescoNoble1985/isi.mod,TITLE Cardiac second inward current\r\nCOMMENT...,None,1,2025-10-19 15:14:43
621,624,c079f94be2f92d61be6a10d2b1f011e2a6679964bb9271...,a128858296997500d88c862e3027013a562b3b903e424d...,1,https://modeldb.science/84589?tab=2&file=eaps/...,https://modeldb.science/getModelFile?model=845...,eaps/mod/kaprox.mod,: Copyright (c) California Institute of Techno...,None,1,2025-10-19 15:14:45
625,628,9c4f6f7a24fecca13895df07df6db72c6ce269ff5b0801...,63decbeaf382ff47652e5f2e3bc54b253e56fab9e1aa70...,1,https://modeldb.science/136095?tab=2&file=ncde...,https://modeldb.science/getModelFile?model=136...,ncdemo/AMPAr.mod,NEURON { POINT_PROCESS AMPAr }\n\nPARAMETER {...,None,1,2025-10-19 15:14:45
641,644,dc268641ef30ec45575a83f2c4826dee807d4edb395f0d...,2a539b2351e11ddde09fa29b8a976607012a3172356cc1...,1,https://modeldb.science/37819?tab=2&file=thal_...,https://modeldb.science/getModelFile?model=378...,thal_aug_resp/kdr.mod,NEURON { SUFFIX kdr }\n \nNEURON { USEION k R...,None,1,2025-10-19 15:14:46
643,646,d66ae67e11d63dc9799cf2df8ec9cf5179a0439045f94e...,9c38d6cd8940be38929cd7f34df9ca66868b7ee429b471...,8,https://modeldb.science/182134?tab=2&file=hfo_...,https://modeldb.science/getModelFile?model=182...,hfo_model/mod/kapyrkop.mod,COMMENT\n\n//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%...,None,1,2025-10-19 15:14:46
717,720,9ec536878ec419509adc2dbe6a1927a40af875a98ed663...,90e02ad710ebe7263955e6cf7ef38826eeef037b203c61...,1,https://modeldb.science/84589?tab=2&file=eaps/...,https://modeldb.science/getModelFile?model=845...,eaps/mod/can.mod,: Copyright (c) California Institute of Techno...,None,1,2025-10-19 15:14:52
734,737,e4a9c80ab18cb727f83fdcddd39485d5c432115f1d128d...,22e3a964f26cae6fc7e77d11200ab36fbb5c06b1355a03...,2,https://modeldb.science/12631?tab=2&file=lytto...,https://modeldb.science/getModelFile?model=126...,lytton97b/pregen.mod,": $Id: pregen.mod,v 1.13 1996/04/07 16:18:19 b...",None,1,2025-10-19 15:14:53
824,827,e69c59be20a70ff0b00fe25d121d65f2a3862b425ca232...,3c43704feeb37505d1e63bf14af27291141d0434dddfdf...,2,https://modeldb.science/116859?tab=2&file=ctxn...,https://modeldb.science/getModelFile?model=116...,ctxnet_v7/GABAa.mod,NEURON { POINT_PROCESS GABAa }\n\nPARAMETER {...,None,1,2025-10-19 15:15:00
855,858,e48a8cc099e179a30038b3cd83950de3d9e13529f1c8b5...,2cd89524cdfc144e9d78403c61ad6df1423028044e64b1...,3,https://modeldb.science/186768?tab=2&file=Sanj...,https://modeldb.science/getModelFile?model=186...,SanjayEtAl2015/iholmw.mod,": $Id: iholmw.mod,v 1.2 2010/11/30 16:34:22 sa...",None,1,2025-10-19 15:15:02
857,860,3920669e8369dacfae16c6c774655993d4c7864a9c8eb0...,6e5ea7f0df96f3093231d02e9a4711f312f62614f079d9...,8,https://modeldb.science/182134?tab=2&file=hfo_...,https://modeldb.science/getModelFile?model=182...,hfo_model/mod/iholmkop.mod,COMMENT\n\n//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%...,None,1,2025-10-19 15:15:03
869,872,bb3423e0dd0807606fb68954ad8a0f159177a9bada5e2e...,a893a1897d9e5642c8eaa3ddf29ab0b687b9006a313f1c...,2,https://modeldb.science/185858?tab=2&file=CaHD...,https://modeldb.science/getModelFile?model=185...,CaHDemo/ihlts.mod,UNITS {\n (mA) = (milliamp)\n (mV) = (milliv...,None,1,2025-10-19 15:15:03
873,876,6c24d97a4b0a010e2cdbe9e6dd3ba7a60f01aff5cab03b...,ff384a3199f64d592943504fb0beb9d61df32575dca736...,8,https://modeldb.science/182134?tab=2&file=hfo_...,https://modeldb.science/getModelFile?model=182...,hfo_model/mod/ihpyrkop.mod,COMMENT\n\n//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%...,None,1,2025-10-19 15:15:04
947,950,55e57d745221229394c3b22845c215e4a076ecbc137b2d...,dd5fedc713b1f2cfe2416c564cacf58dbe9239f149283f...,1,https://modeldb.science/37819?tab=2&file=thal_...,https://modeldb.science/getModelFile?model=378...,thal_aug_resp/AMPA.mod,NEURON {POINT_PROCESS AMPA}\n\nPARAMETER {\n ...,None,1,2025-10-19 15:15:09
1014,1017,8bb1c0f7f5bb346ca4039684bf5f2c38402a398764edef...,8989ddc64224aa8d00a40b687303b872c0ba1aeb9d0559...,1,https://modeldb.science/144520?tab=2&file=DiFr...,https://modeldb.science/getModelFile?model=144...,DiFrancescoNoble1985/if.mod,TITLE Sodium/Calcium Cardiac hyperpolarizing I...,None,1,2025-10-19 15:15:14
1023,1026,8d57b88e925ce7840ac0d48c09e7e551feffcbfb20b20f...,45f3ab1fde9608c99679aa9473c70e094f8550a51f4b3e...,1,https://modeldb.science/144520?tab=2&file=DiFr...,https://modeldb.science/getModelFile?model=144...,DiFrancescoNoble1985/cadynam.mod,TITLE Cardiac intracellular calcium accumulati...,None,1,2025-10-19 15:15:15
1040,1043,d607448500d0851557f3aedbb2d58d35d22cba228d6dae...,6ac767728e0adfd4da71cd10f507a9b18fec0248baa6a4...,8,https://modeldb.science/182134?tab=2&file=hfo_...,https://modeldb.science/getModelFile?model=182...,hfo_model/mod/nafolmkop.mod,COMMENT\n\n//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%...,None,1,2025-10-19 15:15:16
1144,1102,e8c7fdfbc04565d7b0c7b81b2289cd390a25f170a6765b...,5c726c4aca4ef8ca421ddc443e54d9804dfbb970f704cc...,1,https://modeldb.science/9889?tab=2&file=lytton...,https://modeldb.science/getModelFile?model=988...,lytton97/GABAB1.mod,NEURON { POINT_PROCESS GABAB1 }\n: Simple s...,None,1,2025-10-19 15:15:23
1166,1169,635d09c4f23db4a4ad832e10b5aaa6eeaf518587d1ffc6...,4d54d933bb593b3dedc43a326d5772f0171b26a0256094...,1,https://modeldb.science/144520?tab=2&file=DiFr...,https://modeldb.science/getModelFile?model=144...,DiFrancescoNoble1985/inaca.mod,TITLE sodium calcium exchange\r\nCOMMENT\r\n\t...,None,1,2025-10-19 15:15:25
1211,1214,898e0e497bbb8349f0ce0a13bcc02786b56929d66d5ce0...,9d8fb9eb77288795066e865cef495a77951565cb47136c...,2,https://modeldb.science/7400?tab=2&file=lytton...,https://modeldb.science/getModelFile?model=740...,lytton99/kdr.mod,NEURON { SUFFIX kdr }\n \nNEURON { USEION k W...,None,1,2025-10-19 15:15:28
1216,1219,1b08c84bf6c17499388206330bd3fa342725d452b1d9df...,de757e995a1c4ea3272db5fb36961a2999b85ca36668b9...,1,https://modeldb.science/144520?tab=2&file=DiFr...,https://modeldb.science/getModelFile?model=144...,DiFrancescoNoble1985/ibg.mod,TITLE sodium Background Current\r\nCOMMENT\r\n...,None,1,2025-10-19 15:15:28
1236,1239,6832d2e765941d8f275cd645a2d427530e6440a117c489...,19512119e7989e88c6d321e5262acbcec26b425ac6ca99...,1,https://modeldb.science/64229?tab=2&file=netmo...,https://modeldb.science/getModelFile?model=642...,netmod/parbush/nap.mod,NEURON { SUFFIX nap }\nNEURON { USEION na WRIT...,None,1,2025-10-19 15:15:29

In [7]:
all_inc_files

[]

In [ ]:
unique_inc_files = pd.DataFrame(all_inc_files).drop_duplicates(subset=['inc_url'])

In [6]:
unique_inc_files

Empty DataFrame
Columns: []
Index: []