# Import Libaries and Functions

In [1]:
from _utils import *

##  Google Sheet Label Data

In [2]:
# Open the sheet by name
sheet = client.open("label_df").sheet1

# Read sheet data into DataFrame
data = sheet.get_all_records()
label_df = pd.DataFrame(data)

label_df_long = (
    label_df
    .assign(
        robert_subtype_label=label_df['robert_subtype_label']
        .str.split(' \|\| ')
    )
    .explode('robert_subtype_label')
    .assign(
        robert_subtype_label=lambda df: df['robert_subtype_label']
        .str.strip()
        .replace("", pd.NA)
    )
)

## Subtypes that the GPT dataset is missing

- All of them are custom subtypes except for I Other (Modulator-Activated)

In [3]:
INNA_SUBTYPES_ONLY = label_df.query("robert_subtype_label == ''")["original_subtype_label"].tolist()

In [4]:
INNA_SUBTYPES_ONLY

['Exclude - Not on Model DB',
 'Exclude - Old Architecture',
 'Exclude - Accumulation Mechanism',
 'I Ca (HVA)',
 'I K (Ultra Rapid Shaker-related Cardiac)',
 'I K (Resistent Persistent)',
 'I Kx (Photoreceptor)',
 'I Na (Resurgent)',
 'I Leak (General)',
 'I Other (Modulator-Activated)',
 'Neither - Utility',
 'Neither - Non-Neural',
 'Neither - Clamp',
 'Neither - Accumulation Mechanism',
 'Neither - Localized Reactions',
 'Neither - Artificial Cell',
 'Neither - Gap Junction']

In [5]:
XZ_SUBTYPES = label_df.query("original_type_label in ['Exclude','Neither']")["original_subtype_label"].tolist()
XZ_SUBTYPES

['Exclude - Not on Model DB',
 'Exclude - Old Architecture',
 'Exclude - Accumulation Mechanism',
 'Neither - Utility',
 'Neither - Non-Neural',
 'Neither - Clamp',
 'Neither - Accumulation Mechanism',
 'Neither - Localized Reactions',
 'Neither - Artificial Cell',
 'Neither - Gap Junction']

## Subtypes that Annotation Set is missing

In [6]:
label_df.query("gpt_only == 'y'")

,original_type_label,original_subtype_label,robert_subtype_label,new_subtype_label,gpt_only
51,I Other,I Other (NKCC1 Transporter),NKCC1,I Other (Transporter),y
54,I Other,I Other (Na Glutamate),Na+-glutamate transporter,I Other (Transporter),y
55,I Other,I TRP (M4-subtype),I TRPM4,I Other (Rare),y
63,R Dopamine,R Dopamine (D1),D1,R Other (Rare),y
65,R Glutamate,R Glutamate (Kainate),Kainate,R Other (Rare),y
66,R Sensory,R Sensory (General),Sensory Receptors,R Other (Rare),y
67,R Other,R Other - IP3,IP3,R Other (Rare),y

## JSON File

In [7]:
json_df = pd.read_json("../data/raw/mod_files.json")

In [8]:
json_df

,row_id,file_hash,raw_sha,count,url,download_url,content,error_code
0,1,f8be35d0c20d1b1f3de4c44323e1780ee24f06893b6364...,67b75245b9690ce219f34a5905425672dcb5c0661a885f...,6,https://modeldb.science/183300?tab=2&file=Shor...,https://modeldb.science/getModelFile?model=183...,TITLE Sodium persistent current\n\nCOMMENT\n ...,None
1,2,e97ca8a7f9734805832e5ae75442d19d3d7796b9a24190...,b45c13164f1eeaf4ba61ee8522304f7382fa0541831b1a...,1,https://modeldb.science/223649?tab=2&file=Altu...,https://modeldb.science/getModelFile?model=223...,TITLE K-A channel from Klee Ficker and Heinema...,None
2,3,b428f4a84f4302dd5e9139beb678039621e4ee5e88b780...,b720bf29848dde82785dd101105f185ebcf9affa081dfd...,1,https://modeldb.science/3511?tab=2&file=mcn1/m...,https://modeldb.science/getModelFile?model=351...,INDEPENDENT {t FROM 0 TO 1 WITH 1 (ms)}\n\nNEU...,None
3,4,606423f8f4a4f406f3387c7ee6f142bd121237272c347d...,81645a02d4dbf324cf8b82e8f31bda2ce46c3753f7a8ac...,1,https://modeldb.science/262115?tab=2&file=demo...,https://modeldb.science/getModelFile?model=262...,TITLE multiple GABAa receptors\n\nCOMMENT\n---...,None
4,5,99713c0032634e96cc7cde2dce02d8aa2baf75ad4cc835...,5fe32f050754f534d60c7c126ecd805216089cd0594062...,1,https://modeldb.science/150288?tab=2&file=KimE...,https://modeldb.science/getModelFile?model=150...,:Interneuron Cells to Pyramidal Cells GABA wit...,None
...,...,...,...,...,...,...,...,...
5128,5129,79b0488211bde2819176d272a3baf1ea494f7a15b602a7...,7d66f936b9aff684c32bf25234f39c9e755d0fcda38a57...,9,https://modeldb.science/65218?tab=2&file=nrntr...,https://modeldb.science/getModelFile?model=652...,None,403
5129,5130,d8008fe9dc4f90a8bb5484995e07190bda986f48d36bd2...,309c68434d3809f6fd2d547a9869f202800320cc6e7a52...,1,https://modeldb.science/266989?tab=2&file=VMTh...,https://modeldb.science/getModelFile?model=266...,TITLE Hippocampal HH channels\n: \n:\n: Fast N...,None
5130,5131,026e11a7203d24881dcf93b0c7c7fb7d15e6b7dd3d03d4...,8f8e9c80af3b9d715be639e6fa40670269332ae9bc264e...,1,https://modeldb.science/194897?tab=2&file=Dura...,https://modeldb.science/getModelFile?model=194...,": $Id: nsloc.mod,v 1.7 2013/06/20 salvad $\n:...",None
5131,5132,e772fbe270f6fca1c2ee2c7df9a509b4b92ae03bc33cec...,611ae45451e170f8efed72e9f62bae93774a9e2bb9338a...,3,https://modeldb.science/231427?tab=2&file=repr...,https://modeldb.science/getModelFile?model=231...,TITLE AMPA receptor-one of the two input stimu...,None
5132,5133,a9a9d90c28540c114fd8617df170b069cc586eb40b24cb...,256544e26c85c9108832faff4d57a9f70859e58beeab03...,6,https://modeldb.science/266799?tab=2&file=PRC_...,https://modeldb.science/getModelFile?model=266...,TITLE Voltage-gated low threshold potassium cu...,None

## Annotated Excel Sheet

In [9]:
fp = "../data/raw/model_db_annotations.xlsx"
raw_ant_df_wide = pd.read_excel(fp).query("annotated == 'y'")

missing_subtype1_df = raw_ant_df_wide[raw_ant_df_wide["subtype_1"].isna()]

raw_ant_df_long = (raw_ant_df_wide
    .melt(
        id_vars=[col for col in raw_ant_df_wide.columns if col not in ['subtype_1', 'subtype_2', 'subtype_3', 'subtype_4', 'subtype_5']],
        value_vars=['subtype_1', 'subtype_2', 'subtype_3', 'subtype_4', 'subtype_5'],
        var_name="subtype_num",
        value_name="original_subtype_label"
    ))


ant_df_long = (raw_ant_df_long
    .dropna(subset=["original_subtype_label"])
    #Exclusion Criteria here 
    .query("subtype_confidence != '1 - Not confident at all'")
    .query("type != 'Exclude'")
    .drop(columns=['raw_sha','count','url','mod_file','ask_robert','annotated','Robert reviewed','subtype_num'])
    .merge(label_df, on="original_subtype_label", how="left")
    .sort_values('row_id')
    .query("type != 'I Multi'")
    .query("type != 'R Multi'")
    ).drop(columns=["robert_subtype_label"])

/home/imc33/.conda/envs/nn/lib/python3.11/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
/home/imc33/.conda/envs/nn/lib/python3.11/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed

In [10]:
raw_ant_df_long.to_csv("../data/pipeline/ant_with_excluded_samples.csv")

## GPT-4
- These are the subtypes present in our 1k annotation set that are missing from GPT
- Not shown, the GPT dataset included the following: "D1', 'D2', 'Dopaminergic Receptor', 'M1', 'M2', 'M3', 'M4'" which are missing form our 1k dataset

In [11]:
raw_raw_gpt_df = pd.read_csv("../data/raw/mod_files_gpt.csv")

In [12]:
raw_gpt_df = pd.read_csv("../data/raw/mod_files_gpt.csv", usecols=["hash","currents_at_least_3"]).rename(columns={"currents_at_least_3":"gpt_pred"})
raw_gpt_df.head()

,hash,gpt_pred
0,cf53b079807fc6711d9563031aae227dd1a73cf5add973...,"[""IK Skca""]"
1,04c32cd101754ad7f2eaf278919c6ce85b8a7d67149fca...,"[""I Potassium"", ""I Calcium"", ""NMDA"", ""I Sodium""]"
2,2d3c5c121271cfad6d2e35db7d2c418de64f97e57c20a0...,"[""I T low threshold""]"
3,e2f71ea16f8378b3cf0670f9bd5e457634824ab9ee8a7c...,"[""I K""]"
4,04860f65d331d381e779e488566f95ab0e1fa4960b50a7...,[]

In [13]:
#'D1', 'D2', 'Dopaminergic Receptor', 'M1', 'M2', 'M3', 'M4'
#label_df_long[label_df_long.robert_subtype_label.isna()]

In [14]:
ANNOTATED_SAMPLES = ant_df_long["file_hash"].tolist()

In [15]:
len(ANNOTATED_SAMPLES)

1021

In [16]:
gpt_df2 = (
    raw_gpt_df
    .query("hash in @ANNOTATED_SAMPLES")
    .assign(
        gpt_pred=lambda df: df["gpt_pred"].apply(
            lambda x: ast.literal_eval(x) if isinstance(x, str) else x
        )
    )
    .explode("gpt_pred", ignore_index=True)
    .assign(gpt_pred=lambda df: df["gpt_pred"].apply(lambda x: x.strip() if isinstance(x, str) else x))
    .assign(gpt_pred=lambda df: df["gpt_pred"].replace("", pd.NA))
    .dropna(subset=["gpt_pred"])  # <-- drop rows where gpt_pred is NA
    .merge(label_df_long, how="left", left_on="gpt_pred", right_on="robert_subtype_label")          
)

In [17]:
gpt_df2

,hash,gpt_pred,original_type_label,original_subtype_label,robert_subtype_label,new_subtype_label,gpt_only
0,cf53b079807fc6711d9563031aae227dd1a73cf5add973...,IK Skca,I K,I K (Ca-Activated - Sk),IK Skca,I K (Ca-activated),
1,f93e2a97461e26fd22b4a0306da98ccdcc65858623a336...,I K,I K,I K (Delayed Rectifier),I K,I K (Delayed Rectifier),
2,241fe560ad656781054be429af7c5cee507bae0a0383c8...,Kir,I K,I K (IR),Kir,I K (Rare),
3,32825343680dec678864c7c0be7164772f152f51be1878...,Ca pump,I Ca,I Ca (Ca Pump),Ca pump,I Ca (Rare),
4,67082462e039c1300522e57313f509a1987e2988a20457...,I Potassium,I K,I K (General),I Potassium,I K (Rare),
...,...,...,...,...,...,...,...
755,3c251d45f8747a637de413c987d0c55aa3cd90fa9564d4...,I A,I K,I K (A-Type Transient),I A,I K (A-type),
756,353958b6a829992f9c5216e0c879a23ca3d4ffc319774e...,GabaA,R GABA,R GABA (type A),GabaA,R GABA,
757,49786cb42f51c10c434dd06e34f157ff9134b5c8758ad5...,GabaB,R GABA,R GABA (type b),GabaB,R GABA,
758,fc65c9b5c0fb86232d07e57c29d1cb3efe27821b224208...,"I Na,t",I Na,I Na (Transient),"I Na,t",I Na (Transient),
759,b408003421870590bb819f81765f2bd5b9f2f90102b5f3...,I T low threshold,I Ca,I Ca (T-type LT),I T low threshold,I Ca (T-type LT),

## GPT predicted mixes for these (#todo)

In [18]:
View(gpt_df2[gpt_df2.hash.duplicated(keep=False)].sort_values("hash"))

                                                                 hash            gpt_pred original_type_label        original_subtype_label robert_subtype_label        new_subtype_label gpt_only
496  009c5ef10778371f25f95c9ad812c6f628c8f2a7bd7f0638d151bce8c9b4ec06         I Potassium                 I K                 I K (General)          I Potassium               I K (Rare)
494  009c5ef10778371f25f95c9ad812c6f628c8f2a7bd7f0638d151bce8c9b4ec06                NMDA         R Glutamate            R Glutamate (NMDA)                 NMDA       R Glutamate (NMDA)
495  009c5ef10778371f25f95c9ad812c6f628c8f2a7bd7f0638d151bce8c9b4ec06           I Calcium                I Ca                I Ca (General)            I Calcium              I Ca (Rare)
351  04fdb27c5f82a7ebeb4cc1f5ddd7d02d6f3f638e740c1e77c7ec261364390a22               GabaB              R GABA               R GABA (type b)                GabaB                   R GABA
350  04fdb27c5f82a7ebeb4cc1f5ddd7d02d6f3f638e740c1e77c7ec261364390a22               GabaA              R GABA               R GABA (type A)                GabaA                   R GABA
172  0e8bdecd6d7f215aa757f7bc7eb77b993ea69333cbd59b47ebcdd4ffeb61c139         I Potassium                 I K                 I K (General)          I Potassium               I K (Rare)
173  0e8bdecd6d7f215aa757f7bc7eb77b993ea69333cbd59b47ebcdd4ffeb61c139            I Sodium                I Na                I Na (General)             I Sodium           I Na (General)
117  128082167b13809d60218d17079efaf94ded70abecd71db32ee535ee86c90cb6          I Chloride                I Cl                I Cl (General)           I Chloride                    I Cl
118  128082167b13809d60218d17079efaf94ded70abecd71db32ee535ee86c90cb6          I Cl, leak                I Cl                   I Cl (Leak)           I Cl, leak                    I Cl
119  1bb503d7822eeed6ab3e48a83ecfadc2b82d47643b8f33a769ad95b58f00ebc7          I Chloride                I Cl                I Cl (General)           I Chloride                    I Cl
120  1bb503d7822eeed6ab3e48a83ecfadc2b82d47643b8f33a769ad95b58f00ebc7              I_HCO3             I Other                I Other (HCO3)               I_HCO3           I Other (Rare)
696  1e19199e4ff21181070c02c3d36661463b5444de20c225150d51ff161e0bdb71                 IP3             R Other                 R Other - IP3                  IP3           R Other (Rare)        y
695  1e19199e4ff21181070c02c3d36661463b5444de20c225150d51ff161e0bdb71             Ca pump                I Ca                I Ca (Ca Pump)              Ca pump              I Ca (Rare)
693  2174270f39555d14a3e156bc4354da3bc463605842d6a66a9138ae30ae7bec2e               I CAN             I Other  I (Nonspecific Ca-Activated)                I CAN           I Other (Rare)
694  2174270f39555d14a3e156bc4354da3bc463605842d6a66a9138ae30ae7bec2e             I TRPM4             I Other            I TRP (M4-subtype)              I TRPM4           I Other (Rare)        y
706  22afb4409e2101df28fa767e6d6f770cbd717fc2a97e0536fe9e6536ab46d41b                 I N                I Ca                 I Ca (N-Type)                  I N               I Ca (HVA)
707  22afb4409e2101df28fa767e6d6f770cbd717fc2a97e0536fe9e6536ab46d41b  I L high threshold                I Ca              I Ca (L-Type HT)   I L high threshold               I Ca (HVA)
291  256cee41180dc2326ee526e8ec7b7348fe2e929ecf85c0644d4eaa70b14fea32           I Calcium                I Ca                I Ca (General)            I Calcium              I Ca (Rare)
292  256cee41180dc2326ee526e8ec7b7348fe2e929ecf85c0644d4eaa70b14fea32                NMDA         R Glutamate            R Glutamate (NMDA)                 NMDA       R Glutamate (NMDA)
594  2648e4c41271dc5141dbf0faff9ed9d5c5672b88a006103531a7d374f0184d9d           I Calcium                I Ca                I Ca (General)            I Calcium              I Ca (Rare)
595  2648e4c41271dc5141dbf0faff9ed9d5c5672b88a006103531a7d374f0184d9d                NMDA         R Glutamate            R Glutamate (NMDA)                 NMDA       R Glutamate (NMDA)
365  285fa3f533c1d6a59160f7873f14eedc5f2ec8d0d61d1aaccf9fc8de5cf28ec7                NMDA         R Glutamate            R Glutamate (NMDA)                 NMDA       R Glutamate (NMDA)
364  285fa3f533c1d6a59160f7873f14eedc5f2ec8d0d61d1aaccf9fc8de5cf28ec7           I Calcium                I Ca                I Ca (General)            I Calcium              I Ca (Rare)
535  423b0108cca1bfdf1126a879f23f6673c134df8ae80ef0f929bc21481a1abe1b           I Calcium                I Ca                I Ca (General)            I Calcium              I Ca (Rare)
536  423b0108cca1bfdf1126a879f23f6673c134df8ae80ef0f929bc21481a1abe1b                NMDA         R Glutamate            R Glutamate (NMDA)                 NMDA       R Glutamate (NMDA)
443  4378d9c8d89362f1152e65e685ac8581bfcba4668c1e6a0e40b06bf5cf16b2e6             Ca pump                I Ca                I Ca (Ca Pump)              Ca pump              I Ca (Rare)
442  4378d9c8d89362f1152e65e685ac8581bfcba4668c1e6a0e40b06bf5cf16b2e6           I Calcium                I Ca                I Ca (General)            I Calcium              I Ca (Rare)
560  45f2f9b53fa2dc30420af8b53dc7d11bd55ad4c9387c52cfe1dfe9346360f470           I Calcium                I Ca                I Ca (General)            I Calcium              I Ca (Rare)
561  45f2f9b53fa2dc30420af8b53dc7d11bd55ad4c9387c52cfe1dfe9346360f470             Ca pump                I Ca                I Ca (Ca Pump)              Ca pump              I Ca (Rare)
562  45f2f9b53fa2dc30420af8b53dc7d11bd55ad4c9387c52cfe1dfe9346360f470     Na/Ca exchanger             I Other     I Other (Na/Ca exchanger)      Na/Ca exchanger    I Other (Transporter)
196  5ddffc37493309840e0a878846c08322c15a2aad5f992e8f9dcceeb594b30ec7          I Cl, leak                I Cl                   I Cl (Leak)           I Cl, leak                    I Cl
197  5ddffc37493309840e0a878846c08322c15a2aad5f992e8f9dcceeb594b30ec7           I Calcium                I Ca                I Ca (General)            I Calcium              I Ca (Rare)
198  5ddffc37493309840e0a878846c08322c15a2aad5f992e8f9dcceeb594b30ec7          I Na, leak                I Na                   I Na (Leak)           I Na, leak              I Na (Leak)
4    67082462e039c1300522e57313f509a1987e2988a204579953ef7a483c1bc4da         I Potassium                 I K                 I K (General)          I Potassium               I K (Rare)
5    67082462e039c1300522e57313f509a1987e2988a204579953ef7a483c1bc4da          I Chloride                I Cl                I Cl (General)           I Chloride                    I Cl
6    67082462e039c1300522e57313f509a1987e2988a204579953ef7a483c1bc4da            I Sodium                I Na                I Na (General)             I Sodium           I Na (General)
702  69b9b260751b45969472fb5738ede4cccd302644ca34b26be1742b798b452963  I L high threshold                I Ca              I Ca (L-Type HT)   I L high threshold               I Ca (HVA)
701  69b9b260751b45969472fb5738ede4cccd302644ca34b26be1742b798b452963                 I N                I Ca                 I Ca (N-Type)                  I N               I Ca (HVA)
379  6d200240baeceadee65078452a426128b81d9fe82f33edf4c6c439a20d44f0f5   I T low threshold                I Ca              I Ca (T-type LT)    I T low threshold         I Ca (T-type LT)
380  6d200240baeceadee65078452a426128b81d9fe82f33edf4c6c439a20d44f0f5             Ca pump                I Ca                I Ca (Ca Pump)              Ca pump              I Ca (Rare)
121  707a6ee88b53e5f21e968701e587cc54ee98fcd996966b7ada14c2febd728bcd         I Potassium                 I K                 I K (General)          I Potassium               I K (Rare)
122  707a6ee88b53e5f21e968701e587cc54ee98fcd996966b7ada14c2febd728bcd           I Calcium                I Ca                I Ca (General)            I Calcium              I Ca (Rare)
123  707a6ee88b53e5f21e968701e587cc54ee98fcd996966b7ada14c2febd728bcd            I Sodium                I Na                I Na (General)             I Sodium           I Na (General)
124  75b7c2d3dc4df4582ea532257613e33aa3d3a8a2853e599c80888e8d6aff6511           I Calcium                I Ca                I Ca (General)            I Calcium              I Ca (Rare)
125  75b7c2d3dc4df4582ea532257613e33aa3d3a8a2853e599c80888e8d6aff6511                AMPA         R Glutamate            R Glutamate (AMPA)                 AMPA       R Glutamate (AMPA)
100  79b9424f34cfe74c9560499cae5cd33226bb8f5acd0d4968fc301202637b28a1             Kainate         R Glutamate         R Glutamate (Kainate)              Kainate           R Other (Rare)        y
99   79b9424f34cfe74c9560499cae5cd33226bb8f5acd0d4968fc301202637b28a1                AMPA         R Glutamate            R Glutamate (AMPA)                 AMPA       R Glutamate (AMPA)
366  7beead7d05b2353090b78cebbce97e8b9662f1a0e75bad0e72d07da95cf40b9f                AMPA         R Glutamate            R Glutamate (AMPA)                 AMPA       R Glutamate (AMPA)
367  7beead7d05b2353090b78cebbce97e8b9662f1a0e75bad0e72d07da95cf40b9f            I Sodium                I Na                I Na (General)             I Sodium           I Na (General)
680  7e16cac52d64a1c7af97c67a5bfce6bd9072ede35aae92e9653091a059ace911           I Calcium                I Ca                I Ca (General)            I Calcium              I Ca (Rare)
681  7e16cac52d64a1c7af97c67a5bfce6bd9072ede35aae92e9653091a059ace911                NMDA         R Glutamate            R Glutamate (NMDA)                 NMDA       R Glutamate (NMDA)
233  881a6233b3d2421b32006497530a61180e116ec6c9dfd56d58cdf3c7e9a3607a               GabaB              R GABA               R GABA (type b)                GabaB                   R GABA
232  881a6233b3d2421b32006497530a61180e116ec6c9dfd56d58cdf3c7e9a3607a               GabaA              R GABA               R GABA (type A)                GabaA                   R GABA
370  8ae54eba01f3e9fa64a79e7658052074d55c75e8c98b80e13b4ea7d89a854ea0            I Sodium                I Na                I Na (General)             I Sodium           I Na (General)
369  8ae54eba01f3e9fa64a79e7658052074d55c75e8c98b80e13b4ea7d89a854ea0                AMPA         R Glutamate            R Glutamate (AMPA)                 AMPA       R Glutamate (AMPA)
638  99ca745b1897a7691b5e9c007675f2d5f1702d132ab5a3e03a346b1d8d850cb1             Kainate         R Glutamate         R Glutamate (Kainate)              Kainate           R Other (Rare)        y
637  99ca745b1897a7691b5e9c007675f2d5f1702d132ab5a3e03a346b1d8d850cb1                AMPA         R Glutamate            R Glutamate (AMPA)                 AMPA       R Glutamate (AMPA)
652  a02ff182eefdc688f3f98afc01715f824f225d18c7a639d819e7c4cf182e7f33                Gaba              R GABA              R GABA (general)                 Gaba                   R GABA
651  a02ff182eefdc688f3f98afc01715f824f225d18c7a639d819e7c4cf182e7f33           I Calcium                I Ca                I Ca (General)            I Calcium              I Ca (Rare)
130  a6ba55b411a55bad7e532249ba28516f44e70acae7541fb493dbf57f19a9dcf7                NMDA         R Glutamate            R Glutamate (NMDA)                 NMDA       R Glutamate (NMDA)
129  a6ba55b411a55bad7e532249ba28516f44e70acae7541fb493dbf57f19a9dcf7           I Calcium                I Ca                I Ca (General)            I Calcium              I Ca (Rare)
375  b498c5becc54e580e0ac04e236516e69f17b28c2a1ced8af71c4eaa3e46405e7            I Sodium                I Na                I Na (General)             I Sodium           I Na (General)
374  b498c5becc54e580e0ac04e236516e69f17b28c2a1ced8af71c4eaa3e46405e7                AMPA         R Glutamate            R Glutamate (AMPA)                 AMPA       R Glutamate (AMPA)
528  bbc3ec30d4dec255705fbf7cfdd2b3f103f650c8eb98ab9a503a7320d4559b71                AMPA         R Glutamate            R Glutamate (AMPA)                 AMPA       R Glutamate (AMPA)
529  bbc3ec30d4dec255705fbf7cfdd2b3f103f650c8eb98ab9a503a7320d4559b71               GabaA              R GABA               R GABA (type A)                GabaA                   R GABA
372  c0516bbe64d9eded07abbdf9e5715fa8d7367d24a0bbcfda62745b782df4b858                AMPA         R Glutamate            R Glutamate (AMPA)                 AMPA       R Glutamate (AMPA)
371  c0516bbe64d9eded07abbdf9e5715fa8d7367d24a0bbcfda62745b782df4b858                NMDA         R Glutamate            R Glutamate (NMDA)                 NMDA       R Glutamate (NMDA)
90   d300040f4a3b6b6bc54c3006b7af792c74b3d0acc556f915da0424c9bd7b3d91                 I K                 I K       I K (Delayed Rectifier)                  I K  I K (Delayed Rectifier)
91   d300040f4a3b6b6bc54c3006b7af792c74b3d0acc556f915da0424c9bd7b3d91              I Na,t                I Na              I Na (Transient)               I Na,t         I Na (Transient)
243  e0e5a1540eb05d4536d5814c9eefff3380badf54c3a960b04e1c68d589d745ae               NKCC1             I Other   I Other (NKCC1 Transporter)                NKCC1    I Other (Transporter)        y
242  e0e5a1540eb05d4536d5814c9eefff3380badf54c3a960b04e1c68d589d745ae          I Chloride                I Cl                I Cl (General)           I Chloride                    I Cl
244  e0e5a1540eb05d4536d5814c9eefff3380badf54c3a960b04e1c68d589d745ae              I_HCO3             I Other                I Other (HCO3)               I_HCO3           I Other (Rare)
191  e2786aa28911aa95dd7eaa6cdcc6926a01a60bda3d605bd6dd55f1addf5179e3                 I K                 I K       I K (Delayed Rectifier)                  I K  I K (Delayed Rectifier)
192  e2786aa28911aa95dd7eaa6cdcc6926a01a60bda3d605bd6dd55f1addf5179e3                  D1          R Dopamine               R Dopamine (D1)                   D1           R Other (Rare)        y
657  e5936cafbf5acbd94c0b0b8f85a19f97bdff54620452435e61209dfbee24e0fb                AMPA         R Glutamate            R Glutamate (AMPA)                 AMPA       R Glutamate (AMPA)
658  e5936cafbf5acbd94c0b0b8f85a19f97bdff54620452435e61209dfbee24e0fb               I CAN             I Other  I (Nonspecific Ca-Activated)                I CAN           I Other (Rare)
659  e5936cafbf5acbd94c0b0b8f85a19f97bdff54620452435e61209dfbee24e0fb                NMDA         R Glutamate            R Glutamate (NMDA)                 NMDA       R Glutamate (NMDA)
601  e92d01894fb69379e1c601a50404ef51979cdf6c2876c60495f814a58a4d081f                 IP3             R Other                 R Other - IP3                  IP3           R Other (Rare)        y
600  e92d01894fb69379e1c601a50404ef51979cdf6c2876c60495f814a58a4d081f     Na/Ca exchanger             I Other     I Other (Na/Ca exchanger)      Na/Ca exchanger    I Other (Transporter)
599  e92d01894fb69379e1c601a50404ef51979cdf6c2876c60495f814a58a4d081f             Ca pump                I Ca                I Ca (Ca Pump)              Ca pump              I Ca (Rare)
446  eeb5b9e4314b5b6ab9dc8f337b438788ee09bb9f7ab45d00cfc86437d374290f         I Potassium                 I K                 I K (General)          I Potassium               I K (Rare)
449  eeb5b9e4314b5b6ab9dc8f337b438788ee09bb9f7ab45d00cfc86437d374290f            I Sodium                I Na                I Na (General)             I Sodium           I Na (General)
447  eeb5b9e4314b5b6ab9dc8f337b438788ee09bb9f7ab45d00cfc86437d374290f           I Calcium                I Ca                I Ca (General)            I Calcium              I Ca (Rare)
448  eeb5b9e4314b5b6ab9dc8f337b438788ee09bb9f7ab45d00cfc86437d374290f          I Chloride                I Cl                I Cl (General)           I Chloride                    I Cl

In [19]:
a = set(gpt_df2["hash"])
b = set(ANNOTATED_SAMPLES)

In [20]:
MISSING_IN_GPT = list(b-a)

In [21]:
missing_gpt_df = pd.DataFrame({
    "hash": MISSING_IN_GPT,
    "gpt_pred_subtype": "Z Neither",
    "gpt_pred_type": "Neither"
})

In [22]:
missing_gpt_df

,hash,gpt_pred_subtype,gpt_pred_type
0,976c2c7b5b0705a376f0a1ff29495e7fe0069d99511831...,Z Neither,Neither
1,3d81c69104a2de304afcbd7fe7696eb82bd7e67b9e1357...,Z Neither,Neither
2,4375ed0f480cbe4572e4b30abcffe052bed63a65aa0265...,Z Neither,Neither
3,1bad59a8ec3db53c72309760b203920cbf091ee4663c58...,Z Neither,Neither
4,9ce2c80b5bd5b8910d2524ec7e6a147d65384d633eb938...,Z Neither,Neither
...,...,...,...
303,a5c0a068f57399a6dbce8e599f6e6caca65a3929f119c5...,Z Neither,Neither
304,a8f449da2d03d1f812909c79ba27ae47a3b542794f4ced...,Z Neither,Neither
305,37bfe228042f79b485a50636a420726a46582a46f4e422...,Z Neither,Neither
306,9bbabc95794782664eff3e6318db36ad8811c38572b48e...,Z Neither,Neither
307,1445ed3ff2af6e46578eb3ffba99d803a964c46ec74d99...,Z Neither,Neither

In [23]:
#gpt_counts = check_map(gpt_df2, "original_subtype_label", "gpt_pred")
#gpt_counts.query("original_subtype_label not in @XZ_SUBTYPES").sort_values("n", ascending=False)
#gpt_counts.query("original_subtype_label not in @XZ_SUBTYPES").query("n <=20").sort_values("n", ascending=False)

In [24]:
RARE_SUBTYPES_GPT = gpt_df2["new_subtype_label"].value_counts().reset_index().query("count <=10")["new_subtype_label"].tolist()

In [25]:
RARE_SUBTYPES_GPT

['I K (Leak)', 'I Cl ', 'R Other (Rare)', 'I Na (Rare)', 'I Na (Leak)']

In [26]:
#todo: NA general,  I Other Nonspecific, I Delayed Recifidwer

In [27]:
gpt_df2

,hash,gpt_pred,original_type_label,original_subtype_label,robert_subtype_label,new_subtype_label,gpt_only
0,cf53b079807fc6711d9563031aae227dd1a73cf5add973...,IK Skca,I K,I K (Ca-Activated - Sk),IK Skca,I K (Ca-activated),
1,f93e2a97461e26fd22b4a0306da98ccdcc65858623a336...,I K,I K,I K (Delayed Rectifier),I K,I K (Delayed Rectifier),
2,241fe560ad656781054be429af7c5cee507bae0a0383c8...,Kir,I K,I K (IR),Kir,I K (Rare),
3,32825343680dec678864c7c0be7164772f152f51be1878...,Ca pump,I Ca,I Ca (Ca Pump),Ca pump,I Ca (Rare),
4,67082462e039c1300522e57313f509a1987e2988a20457...,I Potassium,I K,I K (General),I Potassium,I K (Rare),
...,...,...,...,...,...,...,...
755,3c251d45f8747a637de413c987d0c55aa3cd90fa9564d4...,I A,I K,I K (A-Type Transient),I A,I K (A-type),
756,353958b6a829992f9c5216e0c879a23ca3d4ffc319774e...,GabaA,R GABA,R GABA (type A),GabaA,R GABA,
757,49786cb42f51c10c434dd06e34f157ff9134b5c8758ad5...,GabaB,R GABA,R GABA (type b),GabaB,R GABA,
758,fc65c9b5c0fb86232d07e57c29d1cb3efe27821b224208...,"I Na,t",I Na,I Na (Transient),"I Na,t",I Na (Transient),
759,b408003421870590bb819f81765f2bd5b9f2f90102b5f3...,I T low threshold,I Ca,I Ca (T-type LT),I T low threshold,I Ca (T-type LT),

In [28]:
gpt_df3 = (
    pd.concat(
        [
            gpt_df2
                .drop(columns=["gpt_pred", "robert_subtype_label", "original_subtype_label","gpt_only"])
                .rename(columns={
                    "new_subtype_label": "gpt_pred_subtype",
                    "original_type_label": "gpt_pred_type"
                }),
            missing_gpt_df
        ],
        ignore_index=True
    )
)

In [29]:
gpt_df3

,hash,gpt_pred_type,gpt_pred_subtype
0,cf53b079807fc6711d9563031aae227dd1a73cf5add973...,I K,I K (Ca-activated)
1,f93e2a97461e26fd22b4a0306da98ccdcc65858623a336...,I K,I K (Delayed Rectifier)
2,241fe560ad656781054be429af7c5cee507bae0a0383c8...,I K,I K (Rare)
3,32825343680dec678864c7c0be7164772f152f51be1878...,I Ca,I Ca (Rare)
4,67082462e039c1300522e57313f509a1987e2988a20457...,I K,I K (Rare)
...,...,...,...
1063,a5c0a068f57399a6dbce8e599f6e6caca65a3929f119c5...,Neither,Z Neither
1064,a8f449da2d03d1f812909c79ba27ae47a3b542794f4ced...,Neither,Z Neither
1065,37bfe228042f79b485a50636a420726a46582a46f4e422...,Neither,Z Neither
1066,9bbabc95794782664eff3e6318db36ad8811c38572b48e...,Neither,Z Neither
1067,1445ed3ff2af6e46578eb3ffba99d803a964c46ec74d99...,Neither,Z Neither

## Simulation Features

In [30]:
#todo: remember to change this when we move to the project directory
base_dir = Path("/vast/palmer/scratch/mcdougal/imc33/mod-extract/data/raw/")
folder_path = base_dir / "sim_csvs"

# Read & combine all CSVs
dfs = []
for file in folder_path.glob("*.csv"):
    df = pd.read_csv(file)
    df["source_file"] = file.name
    df["source_folder"] = folder_path.name
    df["mod_file"] = file.stem.split("__")[-1]
    dfs.append(df)

if not dfs:
    raise FileNotFoundError(f"No CSV files found in {folder_path}")

# Concatenate and drop duplicates
combined_df = pd.concat(dfs, ignore_index=True).drop_duplicates()

# Save combined file
out_path = base_dir / "sim_features_combined.csv"
combined_df.to_csv(out_path, index=False)
print(f"Saved combined sim features to {out_path}")

Saved combined sim features to /vast/palmer/scratch/mcdougal/imc33/mod-extract/data/raw/sim_features_combined.csv

In [31]:
combined_df = pd.read_csv("../data/raw/sim_features_combined.csv")

In [32]:
sim_df = (
    combined_df
    .drop_duplicates(subset="mod_file")
    .rename(columns=lambda col: col if col in ['mod_file', 'mod_name'] else f"{col}_simfeat")
    .assign(file_hash=lambda df: df['mod_file'].str.replace(r'\.mod$', '', regex=True))
    .drop(columns=["suffix_simfeat","source_file_simfeat","source_folder_simfeat"])
    .reset_index(drop=True)
)

In [33]:
sim_df.shape

(569, 51)

# Check Rare Labels
- If count < 10, then collapse into another category; if no category fits, then collapse into Rare. If the collapsed subtype is still rare after collapsing then remove.
- These are the subtypes that were rare before the extra annotation in 2025-06-27:
- RARE_SUBTYPES = ['I Na (Rare)',
 'I Ca (Rare)',
 'I K (Leak)',
 'I Other (Rare)',
 'I Na (Leak)',
 'R Other (Rare)',
 'I Cl '] 

- This is the google sheet: https://docs.google.com/spreadsheets/d/1gZ9pdoGwL_jVwC8APBZ_zb0jzLwl2hg3hIdfmLLEmRY/edit?gid=235253285#gid=235253285

In [34]:
#count_df  = get_count_df(ant_df_long, ['type', 'original_subtype_label'])
#View(count_df)

In [35]:
#count_df  = get_count_df(ant_df_long, ['type', 'original_subtype_label'])
count_df2 = get_count_df(ant_df_long, ['type', 'new_subtype_label'])
RARE_SUBTYPES_INNA = count_df2.sort_values(['type','new_subtype_label'], ascending=[True, False]).query("count <= 10")["new_subtype_label"].to_list()

In [36]:
RARE_SUBTYPES_INNA

['I Ca (Rare)',
 'I Cl ',
 'I K (Leak)',
 'I Na (Leak)',
 'I Other (Transporter)',
 'R Other (Rare)']

In [37]:
RARE_SUBTYPES_GPT

['I K (Leak)', 'I Cl ', 'R Other (Rare)', 'I Na (Rare)', 'I Na (Leak)']

In [38]:
RARE_SUBTYPES = list(set(RARE_SUBTYPES_INNA + RARE_SUBTYPES_GPT))

In [39]:
RARE_SUBTYPES

['I Cl ',
 'I Na (Leak)',
 'I Other (Transporter)',
 'I Na (Rare)',
 'I Ca (Rare)',
 'I K (Leak)',
 'R Other (Rare)']

In [40]:
#count_df2.style.apply(highlight_rare_rows, axis=1)
#todo: should we remove those < 10?
#rare_types = count_df2.query('count<10').sort_values('overall_pct', ascending=False)

# Feature Engineering

In [41]:
#ant_df_long[ant_df_long["new_subtype_label"].isna()].sort_values('row_id')

In [42]:
import re

# Regex patterns (non-capturing; match at line start with MULTILINE)
pattern_any = r'^\s*(?:INCLUDE\s+"[^"]+"|#include\s*[<"][^">]+[>"])'
pattern_cap = r'^\s*(?:INCLUDE\s+"[^"]+")'

# json_df2 build
json_df2 = (
    json_df
    .merge(ant_df_long, on=["row_id", "file_hash"], how="inner")
    .assign(
        mod_name = lambda df: df["url"].apply(get_fname),
        suffix = lambda df: df["content"].apply(get_suffix),
        read_ion = lambda df: df["content"].apply(get_read_ion),
        read_ion2 = lambda df: df["read_ion"].apply(
            lambda ion_list: list(set(map_ion(ion) for ion in ion_list)) if isinstance(ion_list, list) else []
        ),
        write_ion = lambda df: df["content"].apply(get_write_ion),
        write_ion2 = lambda df: df["write_ion"].apply(
            lambda ion_list: list(set(map_ion(ion) for ion in ion_list)) if isinstance(ion_list, list) else []
        ),
        parameter = lambda df: df["content"].apply(get_parameter),
        state = lambda df: df["content"].apply(get_derivative),
        net_receive = lambda df: df["content"].apply(get_net_receive),
        point_process = lambda df: df["content"].apply(get_point_process),
        nonspecific_current = lambda df: df["content"].apply(get_nonspecific_current),

        # Discrete features
        states_count = lambda df: df["state"].apply(lambda x: len(x) if isinstance(x, list) else 0),

        # Binary features
        clamp_yn = lambda df: df.apply(lambda row: has_electrode_or_clamp(row["mod_name"], row["content"]), axis=1),
        suffix_yn = lambda df: df["suffix"].apply(
            lambda x: 1 if isinstance(x, list) and len(x) > 0 else (0 if pd.isna(x) or x == "none" else 1)
        ),
        point_process_yn = lambda df: df["point_process"].apply(lambda x: 1 if pd.notna(x) else 0),
        net_receive_yn = lambda df: df["net_receive"].apply(
            lambda x: 1 if isinstance(x, list) and len(x) > 0 else (1 if pd.notna(x) else 0)
        ),
        i_nonspecific_yn = lambda df: df["nonspecific_current"].apply(
            lambda x: 1 if isinstance(x, list) and len(x) > 0 else (1 if pd.notna(x) else 0)
        ),
        not_ion_channel_yn = lambda df: (
            (df["suffix_yn"] == 0) & df["read_ion"].isna() & df["write_ion"].isna() & df["nonspecific_current"].isna()
        ).astype(int),
        not_receptor_yn = lambda df: (
            (df["point_process_yn"] == 0) & (df["net_receive_yn"] == 0)
        ).astype(int),

        has_mg_yn = lambda df: df["content"].apply(has_mg),
        volt_min = lambda df: df["content"].apply(lambda x: extract_voltage_extrema(x)[0]),
        volt_max = lambda df: df["content"].apply(lambda x: extract_voltage_extrema(x)[1]),

        # Include indicators and line counts
        has_include_yn = lambda df: df['content'].str.contains(pattern_any, case=False, na=False, flags=re.MULTILINE),
        has_include_cap_yn = lambda df: df['content'].str.contains(pattern_cap, case=True, na=False, flags=re.MULTILINE),
     #   line_unadj_count = lambda df: df['content'].fillna("").str.count(r'\n') + (df['content'].notna().astype(int)),
     #   line_adj_count = lambda df: df['content'].apply(count_code_lines),

        # Architecture presence (uncomment if desired)
        # has_x86_64 = lambda df: df['url'].str.contains(r"x86_64", case=False, na=False),
    )
    .reset_index(drop=True)
)

	a = 0.2*(-1.0*v+19.26)/(exp((-1.0*v+19.26)/10.0)-1.0)
	a = 0.2*(-v+19.26)/(exp((-v+19.26)/10.0)-1.0)
	alp = 15.69*(-1.0*v+81.5)/(exp((-1.0*v+81.5)/10.0)-1.0)
	alp = 15.69*(-v+81.5)/(exp((-v+81.5)/10.0)-1.0)
	alpm = 0.1967*(-1.0*v+19.88)/(exp((-1.0*v+19.88)/10.0)-1.0)
	alpm = 0.1967*(-v+19.88)/(exp((-v+19.88)/10.0)-1.0)
	alpm = 0.1967*(-1.0*v+19.88)/(exp((-1.0*v+19.88)/10.0)-1.0)
	alpm = 0.1967*(-v+19.88)/(exp((-v+19.88)/10.0)-1.0)
	a = 0.2*(-1.0*v+19.26)/(exp((-1.0*v+19.26)/10.0)-1.0)
	a = 0.2*(-v+19.26)/(exp((-v+19.26)/10.0)-1.0)
	a = 0.2*(-1.0*v+19.26)/(exp((-1.0*v+19.26)/10.0)-1.0)
	a = 0.2*(-v+19.26)/(exp((-v+19.26)/10.0)-1.0)
	alp = scaletau*15.69*(-1.0*v-shiftm+81.5)/(exp((-1.0*v-shiftm+81.5)/10.0)-1.0)
	alp = scaletau*15.69*(-v-shiftm+81.5)/(exp((-v-shiftm+81.5)/10.0)-1.0)
	alpm = 0.1967*(-1.0*v+19.88)/(exp((-1.0*v+19.88)/10.0)-1.0)
	alpm = 0.1967*(-v+19.88)/(exp((-v+19.88)/10.0)-1.0)
	alp = 15.69*(-1.0*v+81.5)/(exp((-1.0*v+81.5)/10.0)-1.0)
	alp = 15.69*(-v+81.5)/(exp((-v+81.5)/10.0)-1.0)
	alp = 15.69*(-1.0*v+81.5)/(exp((-1.0*v+81.5)/10.0)-1.0)
	alp = 15.69*(-v+81.5)/(exp((-v+81.5)/10.0)-1.0)
	alp = 15.69*(-1.0*v+81.5)/(exp((-1.0*v+81.5)/10.0)-1.0)
	alp = 15.69*(-v+81.5)/(exp((-v+81.5)/10.0)-1.0)
	alp = 15.69*(-1.0*v+81.5)/(exp((-1.0*v+81.5)/10.0)-1.0)
	alp = 15.69*(-v+81.5)/(exp((-v+81.5)/10.0)-1.0)
    alpm = 0.1967*(-1.0*v+19.88)/(exp((-1.0*v+19.88)/10.0)-1.0)
    alpm = 0.1967*(-v+19.88)/(exp((-v+19.88)/10.0)-1.0)
	alpm = 0.1967*(-1.0*v+19.88)/(exp((-1.0*v+19.88)/10.0)-1.0)
	alpm = 0.1967*(-v+19.88)/(exp((-v+19.88)/10.0)-1.0)
	a = 0.2*(-1.0*v+19.26)/(exp((-1.0*v+19.26)/10.0)-1.0)
	a = 0.2*(-v+19.26)/(exp((-v+19.26)/10.0)-1.0)
	a = 0.2*(-1.0*v+19.26)/(exp((-1.0*v+19.26)/10.0)-1.0)
	a = 0.2*(-v+19.26)/(exp((-v+19.26)/10.0)-1.0)
	a = 0.2*(-1.0*v+19.26)/(exp((-1.0*v+19.26)/10.0)-1.0)
	a = 0.2*(-v+19.26)/(exp((-v+19.26)/10.0)-1.0)
	a = 0.2*(-1.0*v+19.26)/(exp((-1.0*v+19.26)/10.0)-1.0)
	a = 0.2*(-v+19.26)/(exp((-v+19.26)/10.0)-1.0)
	alp = 15.69*(-1.0*v+81.5)/(exp((-1.0*v+81.5)/10.0)-1.0)
	alp = 15.69*(-v+81.5)/(exp((-v+81.5)/10.0)-1.0)
	alpm = 0.1967*(-1.0*v+19.88)/(exp((-1.0*v+19.88)/10.0)-1.0)
	alpm = 0.1967*(-v+19.88)/(exp((-v+19.88)/10.0)-1.0)
	alpm = 0.1967*(-1.0*v+19.88)/(exp((-1.0*v+19.88)/10.0)-1.0)
	alpm = 0.1967*(-v+19.88)/(exp((-v+19.88)/10.0)-1.0)
	a = 0.2*(-1.0*v+19.26)/(exp((-1.0*v+19.26)/10.0)-1.0)
	a = 0.2*(-v+19.26)/(exp((-v+19.26)/10.0)-1.0)
	a = 0.2*(-1.0*v+19.26)/(exp((-1.0*v+19.26)/10.0)-1.0)
	a = 0.2*(-v+19.26)/(exp((-v+19.26)/10.0)-1.0)
	alp = scaletau*15.69*(-1.0*v-shiftm+81.5)/(exp((-1.0*v-shiftm+81.5)/10.0)-1.0)
	alp = scaletau*15.69*(-v-shiftm+81.5)/(exp((-v-shiftm+81.5)/10.0)-1.0)
	alpm = 0.1967*(-1.0*v+19.88)/(exp((-1.0*v+19.88)/10.0)-1.0)
	alpm = 0.1967*(-v+19.88)/(exp((-v+19.88)/10.0)-1.0)
	alp = 15.69*(-1.0*v+81.5)/(exp((-1.0*v+81.5)/10.0)-1.0)
	alp = 15.69*(-v+81.5)/(exp((-v+81.5)/10.0)-1.0)
	alp = 15.69*(-1.0*v+81.5)/(exp((-1.0*v+81.5)/10.0)-1.0)
	alp = 15.69*(-v+81.5)/(exp((-v+81.5)/10.0)-1.0)
	alp = 15.69*(-1.0*v+81.5)/(exp((-1.0*v+81.5)/10.0)-1.0)
	alp = 15.69*(-v+81.5)/(exp((-v+81.5)/10.0)-1.0)
	alp = 15.69*(-1.0*v+81.5)/(exp((-1.0*v+81.5)/10.0)-1.0)
	alp = 15.69*(-v+81.5)/(exp((-v+81.5)/10.0)-1.0)
    alpm = 0.1967*(-1.0*v+19.88)/(exp((-1.0*v+19.88)/10.0)-1.0)
    alpm = 0.1967*(-v+19.88)/(exp((-v+19.88)/10.0)-1.0)
	alpm = 0.1967*(-1.0*v+19.88)/(exp((-1.0*v+19.88)/10.0)-1.0)
	alpm = 0.1967*(-v+19.88)/(exp((-v+19.88)/10.0)-1.0)
	a = 0.2*(-1.0*v+19.26)/(exp((-1.0*v+19.26)/10.0)-1.0)
	a = 0.2*(-v+19.26)/(exp((-v+19.26)/10.0)-1.0)
	a = 0.2*(-1.0*v+19.26)/(exp((-1.0*v+19.26)/10.0)-1.0)
	a = 0.2*(-v+19.26)/(exp((-v+19.26)/10.0)-1.0)
	a = 0.2*(-1.0*v+19.26)/(exp((-1.0*v+19.26)/10.0)-1.0)
	a = 0.2*(-v+19.26)/(exp((-v+19.26)/10.0)-1.0)

In [43]:
json_df2.query("row_id == 871")

,row_id,file_hash,raw_sha,count,url,download_url,content,error_code,type,subtype_confidence,notes_free_text,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,original_subtype_label,original_type_label,new_subtype_label,gpt_only,mod_name,suffix,read_ion,read_ion2,write_ion,write_ion2,parameter,state,net_receive,point_process,nonspecific_current,states_count,clamp_yn,suffix_yn,point_process_yn,net_receive_yn,i_nonspecific_yn,not_ion_channel_yn,not_receptor_yn,has_mg_yn,volt_min,volt_max,has_include_yn,has_include_cap_yn
676,871,3d746f710fc8d0b06be3d8c0771ab280046d57d60ddc45...,0004eaa8aca0eec6b9b07ab8a16e7017f0afa1fed168e3...,1,https://modeldb.science/230137?tab=2&file=SinK...,https://modeldb.science/getModelFile?model=230...,TITLE Nav1.2 ionic voltage-gated channel with ...,None,I Na,3 - Highly confident,8/9: Updated confidence. NaG,NaN,NaN,NaN,NaN,I Na (General),I Na,I Na (General),,Nav12_a,[na12a],[ena],[e_na],None,[],"{'gbar': 0.1, 'C1C2b2': 16.0, 'C1C2v2': -5.0, ...","[C1, C2, O1, O2, I1, I2]",None,None,None,6,0,1,0,0,0,0,1,0,NaN,NaN,False,False

In [44]:
# Use MultiLabelBinarizer separately for read and write ions
# Reset index before merging to avoid index mismatches
mlb_read = MultiLabelBinarizer()
read_df = pd.DataFrame(mlb_read.fit_transform(json_df2['read_ion2']), 
                                columns=[f'read_{col}_yn' for col in mlb_read.classes_]).reset_index(drop=True)

mlb_write = MultiLabelBinarizer()
write_df = pd.DataFrame(mlb_write.fit_transform(json_df2['write_ion2']), 
                                 columns=[f'write_{col}_yn' for col in mlb_write.classes_]).reset_index(drop=True)

In [45]:
#note: the ones with missing subtype labels are the rare subtypes
#json_df3[json_df3["new_subtype_label"].isna()].shape
json_df3 = json_df2.drop(columns=['read_ion2', 'write_ion2']).join(read_df, rsuffix='_read_dup').join(write_df, rsuffix='_write_dup').dropna(subset=["new_subtype_label"])

In [46]:
json_df3.shape

(1003, 76)

In [47]:
#json_df3

In [48]:
#Number of mod files in sample that have features derived from simulation
json_df3.merge(sim_df, how="inner", on="file_hash").shape[0]

569

In [49]:
json_df4 = json_df3.merge(sim_df, how="left", on="file_hash")

In [50]:
json_df4.columns

Index(['row_id', 'file_hash', 'raw_sha', 'count', 'url', 'download_url',
       'content', 'error_code', 'type', 'subtype_confidence',
       ...
       'ica_interval1_time_min_to_90_max_simfeat',
       'ica_interval1_time_max_to_90_min_simfeat',
       'ica_interval1_initial_val_simfeat', 'ica_interval1_max_val_simfeat',
       'ica_interval1_min_val_simfeat',
       'ica_interval2_time_to_90_recovery_simfeat',
       'ica_interval2_recovery_start_val_simfeat',
       'ica_interval2_final_val_simfeat', 'ica_interval2_max_val_simfeat',
       'ica_interval2_min_val_simfeat'],
      dtype='object', length=126)

In [51]:
EXTERNAL_VALIDATION_SET = json_df4.query("row_id > 1000")["file_hash"].tolist()

In [52]:
sim_df.shape

(569, 51)

In [53]:
print("Total shape", json_df4.shape)
print("Total unique currents/receptors", json_df4["row_id"].nunique())

Total shape (1003, 126)
Total unique currents/receptors 1003

In [54]:
df_pre = json_df4.set_index('file_hash').filter(regex=r'(_yn|_count|new_subtype_label|volt_min|volt_max|_simfeat)$')

In [55]:
json_df4["type"].value_counts()

type
I K         324
Neither     232
I Na        147
I Ca        113
Receptor    104
I H          47
I Other      35
I Cl          1
Name: count, dtype: int64

In [56]:
df_pre["new_subtype_label"].value_counts()

new_subtype_label
Z Neither                  232
I K (A-type)                93
I Na (Transient)            85
I K (Delayed Rectifier)     80
I Ca (HVA)                  72
I K (Ca-activated)          68
I H                         47
I K (M-type)                40
R Glutamate (NMDA)          39
I K (Rare)                  39
R GABA                      33
I Ca (T-type LT)            31
R Glutamate (AMPA)          31
I Na (Rare)                 23
I Na (Persistent)           22
I Other (Leak)              15
I Na (General)              15
I Other (Rare)              11
I Ca (Rare)                 10
I Other (Transporter)        9
I K (Leak)                   4
I Na (Leak)                  2
I Cl                         1
R Other (Rare)               1
Name: count, dtype: int64

In [57]:
df_pre["rare_subtype"] = df_pre["new_subtype_label"].isin(RARE_SUBTYPES)
df_pre.to_csv("../data/pipeline/preprocessed.csv")

## Which samples have sim_feat?

In [58]:
#df_pre[["type", "voltage_10_simfeat"]].query("voltage_10_simfeat.notnull()").type.value_counts()

In [59]:
#df_pre[["new_subtype_label", "voltage_10_simfeat"]].query("voltage_10_simfeat.notnull()").new_subtype_label.value_counts()

## Which samples do not have sim_feat?

In [60]:
#df_pre[["type", "voltage_10_simfeat"]].query("voltage_10_simfeat.isnull()").type.value_counts()

- We would fix 128 samples

In [61]:
#df_pre[["new_subtype_label", "voltage_10_simfeat"]].query("voltage_10_simfeat.isnull()").new_subtype_label.value_counts()

In [62]:
#df_pre[["new_subtype_label", "voltage_10_simfeat", "type"]].query("voltage_10_simfeat.isnull() and type == 'I H'")
# ❌ will raise an error due to `.isnull()` usage

# ✅ Use this instead:
#View(df_pre[["new_subtype_label", "voltage_10_simfeat", "type"]].query("voltage_10_simfeat.isnull() and type == 'I H'"))

In [63]:
#View(ant_df_long.query("file_hash == '4e3f8b76527532d56c76025e03c24814158dc0396cce61bda61f42becabd3fe8'"))

In [64]:
#df_pre[["new_subtype_label", "voltage_10_simfeat"]].query("voltage_10_simfeat.isnull() and type == 'I H'")

In [65]:
#df_pre[df_pre["voltage_10_simfeat"].isnull() & (df_pre["new_subtype_label"] == "Z Neither")].index.to_list()

In [66]:
json_df3[json_df3.new_subtype_label.isna()]
json_df3[json_df3.type.isna()]

Empty DataFrame
Columns: [row_id, file_hash, raw_sha, count, url, download_url, content, error_code, type, subtype_confidence, notes_free_text, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, original_subtype_label, original_type_label, new_subtype_label, gpt_only, mod_name, suffix, read_ion, write_ion, parameter, state, net_receive, point_process, nonspecific_current, states_count, clamp_yn, suffix_yn, point_process_yn, net_receive_yn, i_nonspecific_yn, not_ion_channel_yn, not_receptor_yn, has_mg_yn, volt_min, volt_max, has_include_yn, has_include_cap_yn, read_ca_i_yn, read_ca_o_yn, read_cl_i_yn, read_cl_o_yn, read_e_ca_yn, read_e_k_yn, read_e_na_yn, read_e_other_yn, read_i_cal_yn, read_i_cl_yn, read_i_k_yn, read_i_na_yn, read_i_other_yn, read_k_i_yn, read_k_o_yn, read_na_i_yn, read_na_o_yn, read_other_i_yn, read_other_o_yn, write_ca_i_yn, write_ca_o_yn, write_cl_i_yn, write_cl_o_yn, write_i_cal_yn, write_i_cl_yn, write_i_k_yn, write_i_na_yn, write_i_other_yn, write_k_i_yn, write_k_o_yn, write_na_i_yn, write_na_o_yn, write_other_i_yn, write_other_o_yn, write_unknown_yn]
Index: []

In [67]:
# === Create ../data/pipeline directory if it doesn't exist ===
pipeline_dir = os.path.abspath(os.path.join("..", "data", "pipeline"))
os.makedirs(pipeline_dir, exist_ok=True)

# === 1. Save failed_neither.pkl ===
failed_neither = df_pre[df_pre["voltage_simfeat"].isnull() &
                        (df_pre["new_subtype_label"] == "Z Neither")].index.to_list()

failed_neither_path = os.path.join(pipeline_dir, "failed_neither.pkl")

with open(failed_neither_path, "wb") as f:
    pickle.dump(failed_neither, f)

print(f"✅ Saved {len(failed_neither)} indices to {failed_neither_path}")

# === 2. Save failed_excluded.pkl ===
a = set(raw_ant_df_wide.file_hash)
b = set(df_pre.index)
failed_excluded = list(a - b)

failed_excluded_path = os.path.join(pipeline_dir, "failed_excluded.pkl")

with open(failed_excluded_path, "wb") as f:
    pickle.dump(failed_excluded, f)

print(f"✅ Saved {len(failed_excluded)} excluded items to {failed_excluded_path}")

✅ Saved 232 indices to /vast/palmer/scratch/mcdougal/imc33/mod-extract/data/pipeline/failed_neither.pkl
✅ Saved 294 excluded items to /vast/palmer/scratch/mcdougal/imc33/mod-extract/data/pipeline/failed_excluded.pkl

In [68]:
# Save your variables manually
with open("../data/pipeline/rare_subtypes.pkl", "wb") as f:
    pickle.dump(RARE_SUBTYPES, f)

with open("../data/pipeline/external_validation_set.pkl", "wb") as f:
    pickle.dump(EXTERNAL_VALIDATION_SET, f)

with open("../data/pipeline/annotated_samples.pkl", "wb") as f:
    pickle.dump(ANNOTATED_SAMPLES, f)